import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import Lenis from "lenis";

export const Route = createFileRoute("/pg-programs")({
  head: () => ({
    meta: [
      { title: "Postgraduate Programs — Masters' Union" },
      {
        name: "description",
        content:
          "The MBA that pays for itself before you graduate. ₹33.39L average CTC, 3.03x salary jump, 148 recruiters across 7 PG programmes.",
      },
      { property: "og:title", content: "Postgraduate Programs — Masters' Union" },
      {
        property: "og:description",
        content: "Real revenue, real fund, real placements. Bain, Google, Goldman.",
      },
    ],
  }),
  component: PgProgramsPage,
});

/* ─── Masters' Union accent palette ─── */
const ACCENT = ["#C94A4A", "#9CC58B", "#EBA15A"] as const;

/* ─── Content ─── */
type Cluster = "All" | "Business" | "Technology & Design" | "Specialised";

type Program = {
  cluster: Exclude<Cluster, "All">;
  title: string;
  tag: string;
  hook: string;
  points: string[];
  cta: string;
};

const PROGRAMS: Program[] = [
  {
    cluster: "Business",
    title: "PGP in Technology & Business Management",
    tag: "Flagship · 16 Months",
    hook: "For those who want to run companies, not just work at them.",
    points: [
      "Grades based on revenue, users & NPS — not exams",
      "Run a real e-commerce business (Cohort '25: ₹3.38 Cr revenue)",
      "Manage a ₹5 Cr student investment fund",
      "46M+ content views generated by Cohort 6",
      "Placements: Bain, BCG, McKinsey, Google, Zepto, Axis Capital",
    ],
    cta: "Explore TBM →",
  },
  {
    cluster: "Business",
    title: "PGP TBM — Young Leaders Cohort",
    tag: "Accelerated · 24 Months",
    hook: "For exceptional graduates who don't want to wait two years to lead.",
    points: [
      "Compressed, high-intensity TBM curriculum (200 credits)",
      "Same OutClass: Dropshipping Fair, Investment Fund, Creator Challenge",
      "Mandatory industry internship built in",
      "Designed for 0–1 years experience",
    ],
    cta: "Explore YLC →",
  },
  {
    cluster: "Business",
    title: "PGP in Human Resources & Organisation Strategy",
    tag: "Full Time",
    hook: "For those who want to build and run the organisations others work at.",
    points: [
      "People strategy, org design, culture, and talent systems",
      "OutClass: live org audits with real companies",
      "Career paths: CHRO track, people ops, consulting, founder's office",
    ],
    cta: "Explore HR & Org Strategy →",
  },
  {
    cluster: "Business",
    title: "PGP in Sustainability & Business Management",
    tag: "Full Time",
    hook: "For those building businesses that last beyond a balance sheet.",
    points: [
      "ESG strategy, climate economics, sustainable supply chains",
      "OutClass: live sustainability audits with corporate partners",
      "Career paths: ESG consulting, impact investing, sustainability leadership",
    ],
    cta: "Explore Sustainability →",
  },
  {
    cluster: "Technology & Design",
    title: "PGP in Applied AI & Agentic Systems",
    tag: "Full Time",
    hook: "For those who want to build with AI, not just talk about it.",
    points: [
      "LLMs, agentic workflows, real deployment",
      "OutClass: ship working AI products — evaluated on adoption, not theory",
      "Career paths: AI product, AI consulting, founding engineer, AI strategy",
    ],
    cta: "Explore Applied AI →",
  },
  {
    cluster: "Technology & Design",
    title: "PGP in UI/UX & AI Product Design",
    tag: "Full Time",
    hook: "For those who design what millions of people actually use.",
    points: [
      "Product design, AI-native UX, design systems",
      "Studio model: critique-based, not lecture-based",
      "Career paths: Product designer, UX lead, design founder",
    ],
    cta: "Explore UI/UX & Product Design →",
  },
  {
    cluster: "Specialised",
    title: "PGP in Sports Management & Gaming",
    tag: "Full Time",
    hook: "For those building the business of sport and interactive entertainment.",
    points: [
      "Sports business, franchise management, gaming ecosystems, media rights",
      "OutClass: live projects with franchises, esports orgs, gaming companies",
      "Career paths: franchise ops, esports, sports media, gaming product",
    ],
    cta: "Explore Sports & Gaming →",
  },
];

const TABS: Cluster[] = ["All", "Business", "Technology & Design", "Specialised"];

const PATHWAYS = [
  {
    id: "tbm",
    num: "01",
    label: "Experienced Professionals",
    short: "PGP TBM",
    full: "PGP in Technology & Business Management",
    ideal:
      "Built for ambitious professionals with 1–8 years of experience ready to leap into tech-forward leadership — learn from CXOs of Google, McKinsey & Bain, not textbooks.",
    facts: [
      ["Duration", "16 Months"],
      ["Format", "Full-Time, Opt-in Residential"],
      ["Location", "Gurugram (DLF Cyberpark)"],
      ["Cohort Size", "~120"],
      ["Next Cohort", "June 2026"],
      ["Credits", "120 (InClass + OutClass)"],
    ],
    highlights: [
      ["₹33.39L", "Average CTC"],
      ["₹1.28 Cr", "Highest CTC placed"],
      ["145+", "Marquee recruiters — Google, Flipkart, Zomato"],
      ["₹5 Cr", "Student-led investment fund"],
      ["100+", "VCs at Demo Day"],
      ["11.2%", "Placed as EiR & Chief of Staff at top startups"],
    ],
  },
  {
    id: "ylc",
    num: "02",
    label: "Young Leaders",
    short: "PGP TBM · YLC",
    full: "Young Leaders' Certificate Programme",
    ideal:
      "Designed for fresh graduates and early-career operators (0–1 year experience) who want to fast-track into leadership — with extra foundational depth and a mandatory industry internship.",
    facts: [
      ["Duration", "24 Months"],
      ["Format", "Full-Time, Opt-in Residential"],
      ["Location", "Gurugram (DLF Cyberpark)"],
      ["Cohort Size", "~80"],
      ["Next Cohort", "June 2026"],
      ["Credits", "200 (deeper foundations)"],
    ],
    highlights: [
      ["₹28.24L", "Average CTC"],
      ["₹46.22L", "Highest CTC placed"],
      ["100+", "Recruiting companies across sectors"],
      ["₹2 Cr+", "Earned collectively in Dropshipping Challenge"],
      ["Day 1", "Startup incubation — graduate with a running business"],
      ["1M+", "Followers built via Creator-preneur track"],
    ],
  },
];

const HERO_STATS = [
  { value: "₹33.39L", label: "Average CTC" },
  { value: "3.03x", label: "Salary jump from pre-MBA" },
  { value: "148", label: "Recruiters on campus" },
  { value: "₹593 Cr", label: "Student startup valuation" },
];

const STATS = [
  ["₹33.39L", "Average CTC"],
  ["₹61.98L", "Highest CTC"],
  ["3.03x", "Salary Jump from Pre-MBA"],
  ["148", "Recruiters"],
  ["35+", "International Offers"],
  ["10–20%", "Annual Salary Growth"],
];

const ROLES = [
  "Product Manager",
  "Program Manager",
  "Strategy Associate",
  "Chief of Staff",
  "Entrepreneur in Residence",
  "Manager — Founder's Office",
  "Growth Manager",
  "Business Analyst",
  "Consultant",
  "Brand Marketing",
];

const RECRUITERS = [
  "Google",
  "McKinsey",
  "Bain",
  "BCG",
  "Microsoft",
  "Meta",
  "Zomato",
  "Flipkart",
  "Zepto",
  "Blinkit",
  "Razorpay",
  "Goldman Sachs",
  "Amazon",
  "Kotak IB",
  "Axis Capital",
  "PwC",
];

const ALUMNI_TRANSFORMATIONS = [
  { name: "Shruti Kumari", before: ["Communications Lead", "Adfactors"], during: "Led live brand campaigns for D2C companies", after: ["Brand Marketing", "Flipkart"] },
  { name: "Tushar Chuttani", before: ["Product Associate", "BYJU'S"], during: "Built a D2C brand through the Founder Fellowship", after: ["Entrepreneur in Residence", "mCaffeine"] },
  { name: "Apurv Rathore", before: ["Associate Consultant", "Bain & Co."], during: "Managed a ₹5 Cr student investment fund", after: ["Lead Product Manager", "Sprinklr"] },
  { name: "Gautam Marwah", before: ["Product Manager", "Pine Labs"], during: "Co-founded a fintech startup during the programme", after: ["Chief of Staff", "Kae Capital"] },
  { name: "Tilottama Ghosh", before: ["Analyst", "JP Morgan"], during: "Won national case competition against IIMs", after: ["Associate", "Kotak Investment Banking"] },
  { name: "Manya Parmar", before: ["Consultant", "PwC India"], during: "Built growth strategies for Series A startups", after: ["Program Manager", "Zomato"] },
];

const CURRICULUM_DOMAINS = [
  {
    title: "Communication & Self Development",
    blurb:
      "Master influence — boardroom presentations, high-stakes negotiations, crisp business writing. Build executive presence, EQ, and the storytelling that separates good managers from great leaders.",
    bullets: [
      "Inspiring speeches, persuasive writing, emails that get responses",
      "Productivity systems, personal finance, portfolio building",
      "Leadership, mental models, motivating teams, running meetings",
    ],
    facultyHighlight:
      "Dr. Bhasker Malu · Dr. Francis Rebello (Plan International) · Dr. Rajagopal Raghunathan (UT Austin)",
  },
  {
    title: "Finance & Fintech",
    blurb:
      "From reading a balance sheet to building full financial models. Learn how India's top CFOs think about capital allocation, valuation, and risk — then apply it to fintech, crypto, and real fundraising.",
    bullets: [
      "Statements, budgeting, cost control, advanced Excel",
      "Valuation, modelling, MIS, raising debt & equity capital",
      "Fintech, blockchain, and understanding global financial crises",
    ],
    facultyHighlight:
      "Dr. Garrick Hileman (U. Nicosia) · Dr. Arvind Mayaram (Ex-Finance Secretary, GoI) · Satish Krishnan (Ex-MD, StanChart)",
  },
  {
    title: "Sales & Marketing",
    blurb:
      "The growth playbooks behind Nike, Zerodha, and boAt. From performance marketing and funnel optimisation to community-led growth and brand storytelling — become a full-stack marketer who drives revenue.",
    bullets: [
      "Organic growth, Meta & Google ads, Amazon selling, GTM",
      "Brand building, consumer psychology, CRM, content marketing",
      "Community, personal branding, closing deals via storytelling",
    ],
    facultyHighlight:
      "Elkana Ezekiel (Ex-CMO Samsung) · Arjun Vaidya · Vani Gupta Dandia (Ex-PepsiCo) · Saurabh Sengupta (Ex-SVP Zomato)",
  },
  {
    title: "Management & Strategy",
    blurb:
      "Think like a CEO. From competitive analysis and crisis management to organisational design and global supply chains — the strategic frameworks used at McKinsey, Swiggy, and Softbank.",
    bullets: [
      "Team dynamics, procurement, market analysis, KPI tracking",
      "Strategy, business plans, crisis & organisational alignment",
      "Networking, 7-slide pitches, giving effective feedback",
    ],
    facultyHighlight:
      "Rohit Kapoor (CEO, Swiggy Food) · Dr. Manoj Kohli (Ex-Softbank India) · Dr. Edward Rogers (Ex-CKO, NASA)",
  },
  {
    title: "Product, Tech & AI",
    blurb:
      "Build like a founder, think like a PM, harness AI as a force multiplier. Live e-commerce stores, Figma design, code, no-code MVPs, and AI-powered products — technically dangerous enough to lead any product team.",
    bullets: [
      "E-commerce, design thinking, reading & writing code, dashboards",
      "UI/UX with Figma, no-code app building, product mindset",
      "Prompt engineering, generative AI, building agentic products",
    ],
    facultyHighlight:
      "Monica Jasuja (Mastercard) · Malthi Satish (Ex-Dir PM, PayPal) · Gaurav Mittal (Stripe) · Divij Bajaj (Microsoft)",
  },
];

const OUTCLASS = [
  { eb: "Term 1", t: "Dropshipping Fair", s: "₹3.38 Cr", b: "50 teams. Real products. Real customers on Shopify, Amazon & Flipkart. Cohort '25 total revenue." },
  { eb: "Term 2", t: "Content Creator Challenge", s: "46M+", b: "120+ creators. ₹10L+ prize pool. 80+ live brand assets delivered to real D2C brands in 24 hours." },
  { eb: "Year-round", t: "Student Investment Fund", s: "₹5 Cr", b: "Real corpus. Beaten public markets by 20–25% consistently. 5+ startup co-investments alongside VCs." },
  { eb: "Venture Track", t: "Venture Initiation Programme", s: "₹593 Cr", b: "Combined portfolio valuation. ₹25.24 Cr raised. 6 Shark Tank India appearances. 100+ VCs at Demo Day." },
];

const MODEL = [
  { eb: "InClass", t: "Faculty Who've Done It", b: "30% professors from Harvard, Stanford, Wharton, Kellogg. 50% CEOs and operators. 20% PhD faculty. Every session is a real decision, not a case study." },
  { eb: "OutClass", t: "Your Grade Is Your Revenue", b: "No exams. Grades based on real products, real revenue, real NPS. You run businesses. You manage a fund. You build brands. You pitch to VCs." },
  { eb: "Immersions", t: "India & The World", b: "Full-term Bharat Immersion: 7,000 km, 8 hubs, 20+ cities, 40+ CXO sessions. Global: 8 immersions across 7 countries — INSEAD, Boeing, BMW, London finance desks." },
];

const STARTUPS = [
  ["EIGHT", "5M+ downloads across platforms", "MEDIA · TECH"],
  ["Nivara", "Making fine jewellery sustainable & accessible", "D2C · LUXURY"],
  ["Woody's Pizzeria", "A 1-star to 4.7-star turnaround story", "F&B"],
  ["SeedsAI", "Conversations into enterprise-grade insights", "AI · SAAS"],
  ["PlaySuper", "Gaming culture meets commerce at scale", "GAMING"],
  ["Blue Brew", "Cult denim brand with a Gen Z following", "D2C · FASHION"],
  ["Lexi's", "Bold flavours, top ratings, repeat customers", "F&B"],
  ["JustMyRoots", "Preserving India's culinary heritage at scale", "F&B · LOGISTICS"],
  ["Flourish Foods", "Fortified staples for every Indian kitchen", "F&B · HEALTH"],
  ["Offlyn", "Curated local events for real-world connections", "SOCIAL · TECH"],
  ["Cryptique", "Data tools for the decentralised web era", "WEB3"],
  ["Beyond Veda", "₹2 Cr revenue reimagining ayurveda for Gen Z", "D2C · WELLNESS"],
];

const SHARK_TANK = [
  ["Bullspree", "Season 2", "Dharmil Bavishi", "India's favourite stock market playground"],
  ["Nexera Health", "Season 4", "Himanshu Rajpurohit", "Redefining workplace wellness"],
  ["Hive School", "Season 4", "Nikhil Gaur", "Building India's first Sales School"],
  ["Memotag", "Season 4", "Reyansh Juneja", "AI-driven wearable for dementia care"],
  ["HookD", "Season 5", "Dia Goel", "India's first ready-to-eat non-veg snacking brand"],
  ["Meta Fashion", "Season 5", "Arjun Goel", "Phygital commerce: in-game discovery → fashion"],
];

const FUND_STATS = [
  ["30+", "Startups Incubated"],
  ["₹480 Cr", "Projected FY26 Revenue"],
  ["₹593 Cr", "Total Portfolio Valuation"],
  ["180+", "Jobs Created"],
  ["₹1.2 Cr", "Grants Disbursed"],
];

const IMMERSION_STATS = [
  ["8", "Global Immersions", "across 7 countries"],
  ["8", "Bharat Hubs", "7,000 km across India"],
  ["50+", "1-Day Immersions", "factory floors to boardrooms"],
  ["40+", "CXO Sessions", "with industry leaders"],
];

const IMMERSIONS = [
  { eb: "Campus", t: "DLF Cyberpark, Gurugram", b: "85% of Fortune 500 companies within 2 km. BCG, EY, Gartner an elevator ride away. Recruiters don't fly in — they walk over.", meta: "" },
  { eb: "Bharat Immersion", t: "7,000 km Across India", b: "A full academic term on the road. Chandni Chowk → Dalal Street → Mundra Adani ports → Darjeeling tea estates.", meta: "8 Hubs · 20+ Cities · 40+ CXO Sessions · 50+ One-Day Immersions" },
  { eb: "Global Immersion", t: "8 Immersions Across 7 Countries", b: "INSEAD Paris. NUS Singapore. Babson. SDA Bocconi. London and New York finance desks. Boeing. BMW.", meta: "Paris · Singapore · Boston · Milan · Berlin · London · Canada" },
];

const FACULTY_SPLIT = [
  ["50%", "Industry Practitioners.", "CEOs, founders, operators."],
  ["30%", "Full-Time Faculty.", "PhD educators from IIM Calcutta, Bangalore, Ahmedabad."],
  ["20%", "Visiting Faculty.", "Harvard, Stanford, Wharton, Kellogg, Cornell, MIT Sloan, Imperial, Cambridge."],
];

const COHORT = [
  ["26 yrs", "Avg Age"],
  ["3 yrs", "Avg Work Experience"],
  ["40%", "Female Representation"],
  ["60%", "Engineering Background"],
  ["22+", "States Represented"],
];

const ADMISSIONS_STEPS = [
  ["01", "Apply"],
  ["02", "MU-BAAT"],
  ["03", "Interview"],
  ["04", "Offer"],
  ["05", "Enroll"],
];

const FAQS_LEFT = [
  { q: "Do I need CAT/GMAT scores to apply?", a: "No. We don't require standardised test scores. Our admissions evaluate ambition, grit, and your drive to build — through essays, MU-BAAT, and a personal interview." },
  { q: "Is this equivalent to an MBA?", a: "It covers core MBA subjects plus AI, product management, and startup building — all taught by practicing CXOs from Google, Bain, and Zerodha. Graduates consistently outperform traditional MBA holders in placements." },
  { q: "What outcomes can I expect after graduating?", a: "PGP TBM graduates achieve an average CTC of ₹33.39L (highest ₹1.28 Cr) across roles like Product Manager, Chief of Staff, Strategy Consultant, and Founder. 145+ companies actively recruit from campus." },
  { q: "Can I start a company during the programme?", a: "Yes. Our Founder Fellowship provides ₹40,000/month to up to 25 founders for a year. This has produced 30+ funded startups, including Bullspree (Shark Tank, $1M+ raised) and SeedsAI ($250K raised)." },
];

const FAQS_RIGHT = [
  { q: "What does the programme fee include?", a: "Tuition, campus access, learning resources, industry masterclasses, mentorship, career workshops, and alumni network access. Immersion trips and hostel accommodation are additional." },
  { q: "Are education loans available?", a: "Yes. Masters' Union partners with IDFC First Bank, HDFC Credila, and Tata Capital for flexible education loans at competitive rates." },
  { q: "How do I apply for a scholarship?", a: "Scholarship eligibility is assessed as part of admissions — no separate application. We evaluate every candidate for merit, diversity, and need-based scholarships." },
  { q: "Is the fee the same for PGP TBM and YLC?", a: "Yes, the programme fee is the same for both the 16-month PGP TBM and the 24-month Young Leaders Cohort. YLC includes additional foundational terms at no extra cost." },
];

const FEES = [
  { t: "Education Financing", b: "Partnered with IDFC First Bank, HDFC Credila, and Tata Capital for flexible education loans at competitive rates — accessible regardless of financial background." },
  { t: "9+ Scholarships & Financial Aid", b: "Merit-based, diversity, entrepreneur bursaries, and women-in-leadership awards — one of the most comprehensive scholarship programmes among India's top B-schools." },
  { t: "ROI That Speaks", b: "₹33.39L average CTC, ₹1.28 Cr highest, 145+ marquee recruiters including Bain, McKinsey, Flipkart, and Zomato. Your investment pays for itself many times over." },
];

/* ─── Page ─── */
function PgProgramsPage() {
  useEffect(() => {
    const lenis = new Lenis({ duration: 1.2, smoothWheel: true });
    let rafId = 0;
    const raf = (t: number) => {
      lenis.raf(t);
      rafId = requestAnimationFrame(raf);
    };
    rafId = requestAnimationFrame(raf);
    return () => {
      cancelAnimationFrame(rafId);
      lenis.destroy();
    };
  }, []);

  return (
    <main className="bg-white text-[#1a1a1a] antialiased">
      <Nav />
      <Hero />
      <Pathways />
      <Outcomes />
      <Transformations />
      <Model />
      <Curriculum />
      <Programs />
      <FacultyCohort />
      <Immersions />
      <Entrepreneurship />
      <Admissions />
      <Fees />
      <FAQ />
      <CTA />
    </main>
  );
}

/* ─── Nav ─── */
function Nav() {
  return (
    <div className="pointer-events-none fixed inset-x-0 top-0 z-50 flex items-center justify-between px-6 py-5 md:px-10">
      <Link
        to="/"
        className="pointer-events-auto bg-white/80 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.25em] text-[#1a1a1a]/70 backdrop-blur transition hover:text-[#1a1a1a]"
      >
        ← Masters' Union
      </Link>
      <span className="bg-white/80 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.25em] text-[#1a1a1a]/50 backdrop-blur">
        Postgraduate programmes
      </span>
    </div>
  );
}

/* ─── Atoms ─── */
function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <div className="font-mono text-[11px] uppercase tracking-[0.3em] text-[#1a1a1a]/50">
      {children}
    </div>
  );
}

function SectionHead({
  eb,
  title,
  lede,
}: {
  eb: string;
  title: React.ReactNode;
  lede?: React.ReactNode;
}) {
  return (
    <>
      <Eyebrow>{eb}</Eyebrow>
      <h2 className="font-display mt-3 max-w-[22ch] text-balance text-[clamp(1.6rem,4.2vw,3.2rem)] font-light leading-[1.02] tracking-tight">
        {title}
      </h2>
      {lede && (
        <p className="font-display mt-4 max-w-[58ch] text-[clamp(1rem,1.4vw,1.2rem)] leading-relaxed text-[#1a1a1a]/65">
          {lede}
        </p>
      )}
    </>
  );
}

function StatGrid({
  items,
  cols = 4,
}: {
  items: { value: string; label: string }[];
  cols?: 3 | 4;
}) {
  const colClass = cols === 3 ? "md:grid-cols-3" : "md:grid-cols-4";
  return (
    <div className={`grid grid-cols-2 gap-px border border-black/10 bg-black/10 ${colClass}`}>
      {items.map((s, i) => (
        <div key={i} className="bg-white px-4 py-5 md:px-5 md:py-6">
          <div className="font-display text-[clamp(1.5rem,3vw,2.2rem)] font-thin leading-none tracking-[-0.03em]">
            {s.value}
          </div>
          <div className="mt-2 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
            {s.label}
          </div>
        </div>
      ))}
    </div>
  );
}

/* ─── Hero ─── */
function Hero() {
  return (
    <section className="px-6 pb-12 pt-24 md:px-12 md:pb-16 md:pt-32">
      <div className="mx-auto max-w-6xl">
        <Eyebrow>Postgraduate programmes</Eyebrow>
        <h1 className="font-display mt-4 text-balance text-[clamp(1.9rem,6vw,5.2rem)] font-light leading-[0.94] tracking-tight">
          The MBA that{" "}
          <span className="italic mu-gradient-text">pays for itself</span> before you graduate.
        </h1>
        <p className="font-display mt-6 max-w-[58ch] text-[clamp(1.1rem,1.6vw,1.45rem)] leading-relaxed text-[#1a1a1a]/70">
          PG students generate real revenue, manage a ₹5 Cr investment fund, build personal brands
          with 46M+ reach, and step into roles at Bain, Google and Goldman — with a 3.03× salary
          jump.
        </p>

        <div className="mt-8 flex flex-wrap gap-3">
          <a
            href="#apply"
            className="border-[1.5px] border-transparent bg-[#1a1a1a] px-6 py-4 font-mono text-[11px] uppercase tracking-[0.3em] text-white transition hover:bg-[#1a1a1a]/85"
            style={{
              borderImage:
                "linear-gradient(91deg, #39B5D7 -6%, #F7D544 47%, #E38330 100%) 1",
            }}
          >
            Apply for PG programmes →
          </a>
          <a
            href="#programs"
            className="border border-black/15 bg-white px-6 py-4 font-mono text-[11px] uppercase tracking-[0.3em] text-[#1a1a1a]/80 transition hover:border-black/40"
          >
            Explore the 7 programmes
          </a>
        </div>

        <div className="mt-10">
          <StatGrid items={HERO_STATS} />
        </div>
      </div>
    </section>
  );
}

/* ─── Admission Pathways ─── */
function Pathways() {
  const [pathway, setPathway] = useState("tbm");
  const active = PATHWAYS.find((p) => p.id === pathway)!;
  return (
    <section className="border-t border-black/10 bg-[#fafaf7] px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Admission pathways"
          title={
            <>
              Two programmes. <span className="italic mu-gradient-text">One mission.</span>
            </>
          }
          lede="Choose the pathway that matches your experience level and ambition. Both lead to transformative outcomes."
        />

        <div className="mt-10 grid gap-0 lg:grid-cols-[320px_1fr]">
          <div className="grid grid-cols-2 lg:grid-cols-1">
            {PATHWAYS.map((p, i) => {
              const on = p.id === pathway;
              return (
                <button
                  key={p.id}
                  onClick={() => setPathway(p.id)}
                  className="group relative text-left"
                >
                  <div
                    className="h-[3px] w-full"
                    style={{ background: on ? ACCENT[i] : "rgba(0,0,0,0.08)" }}
                  />
                  <div
                    className={`border border-t-0 px-5 py-6 transition-colors ${
                      on ? "border-black/10 bg-white" : "border-black/8 bg-white/60 hover:bg-white"
                    }`}
                  >
                    <div
                      className="font-display text-[44px] font-thin leading-none tracking-[-0.04em]"
                      style={{ color: on ? ACCENT[i] : "rgba(26,26,26,0.15)" }}
                    >
                      {p.num}
                    </div>
                    <div className="mt-4 font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                      {p.label}
                    </div>
                    <h3 className="font-display mt-1 text-[22px] font-medium leading-tight tracking-tight">
                      {p.short}
                    </h3>
                  </div>
                </button>
              );
            })}
          </div>

          <motion.div
            key={pathway}
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
            className="border border-t-0 border-black/10 bg-white lg:border-t lg:border-l-0"
          >
            <div
              className="h-[3px] w-full"
              style={{ background: ACCENT[PATHWAYS.findIndex((p) => p.id === pathway)] }}
            />
            <div className="p-7 md:p-10">
              <Eyebrow>{active.label}</Eyebrow>
              <h3 className="font-display mt-3 text-[clamp(1.5rem,2.6vw,2.2rem)] font-light leading-[1.1] tracking-tight">
                {active.full}
              </h3>
              <p className="font-display mt-4 max-w-[60ch] text-[15px] leading-relaxed text-[#1a1a1a]/75">
                {active.ideal}
              </p>

              <div className="mt-8 grid grid-cols-2 gap-px border border-black/10 bg-black/10 md:grid-cols-3">
                {active.facts.map(([l, v]) => (
                  <div key={l} className="bg-white px-4 py-4">
                    <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/50">
                      {l}
                    </div>
                    <div className="mt-1.5 text-[13px] font-medium text-[#1a1a1a]">{v}</div>
                  </div>
                ))}
              </div>

              <div className="mt-8">
                <Eyebrow>Programme highlights</Eyebrow>
                <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3">
                  {active.highlights.map(([n, l]) => (
                    <div key={l} className="border border-black/8 bg-[#fafaf7] p-4">
                      <div className="font-display text-[26px] font-thin leading-none tracking-[-0.03em] text-[#1a1a1a]">
                        {n}
                      </div>
                      <div className="mt-2 text-[12px] leading-snug text-[#1a1a1a]/65">{l}</div>
                    </div>
                  ))}
                </div>
              </div>

              <a
                href="#apply"
                className="mt-8 inline-flex items-center bg-[#1a1a1a] px-5 py-3 font-mono text-[11px] uppercase tracking-[0.28em] text-white transition hover:bg-[#1a1a1a]/85"
              >
                Apply for {active.short} →
              </a>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

/* ─── Outcomes ─── */
function Outcomes() {
  return (
    <section className="border-t border-black/10 bg-white px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Career outcomes"
          title={
            <>
              Our graduates don't just get jobs.{" "}
              <span className="italic mu-gradient-text">They get careers.</span>
            </>
          }
          lede="5 graduating cohorts. 148 recruiters. From Google and McKinsey to founding VC-backed startups — here's what happens after Masters' Union."
        />

        <div className="mt-10">
          <StatGrid
            cols={3}
            items={STATS.map(([value, label]) => ({ value, label }))}
          />
        </div>

        <div className="mt-12">
          <Eyebrow>Roles graduates land</Eyebrow>
          <div className="mt-4 flex flex-wrap gap-2">
            {ROLES.map((r) => (
              <span
                key={r}
                className="border border-black/10 px-3 py-1.5 font-mono text-[11px] uppercase tracking-[0.18em] text-[#1a1a1a]/75 transition hover:border-black/35"
              >
                {r}
              </span>
            ))}
          </div>
        </div>

        <div className="mt-10">
          <Eyebrow>148 companies that recruit from us</Eyebrow>
          <div className="font-display mt-4 flex flex-wrap gap-x-8 gap-y-3 text-[15px] text-[#1a1a1a]/75">
            {RECRUITERS.map((r) => (
              <span key={r} className="font-medium">
                {r}
              </span>
            ))}
            <span className="text-[#1a1a1a]/40">+ 130 more</span>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─── Transformations ─── */
function Transformations() {
  return (
    <section className="border-t border-black/10 bg-[#fafaf7] px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Transformation stories"
          title={
            <>
              What happens to people{" "}
              <span className="italic mu-gradient-text">who join?</span>
            </>
          }
          lede="Not testimonials. Real career transformations — before, during, and after Masters' Union."
        />

        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {ALUMNI_TRANSFORMATIONS.map((t, i) => {
            const color = ACCENT[i % ACCENT.length];
            return (
              <motion.article
                key={t.name}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, delay: i * 0.05, ease: [0.22, 1, 0.36, 1] }}
                className="border border-black/8 bg-white"
              >
                <div className="flex items-center justify-between border-b border-black/8 px-5 py-3">
                  <span
                    className="font-display text-[28px] font-thin leading-none tracking-[-0.04em]"
                    style={{ color }}
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="font-mono text-[10px] uppercase tracking-[0.24em] text-[#1a1a1a]/55">
                    {t.name}
                  </span>
                </div>
                <div className="p-5">
                  <div>
                    <div className="font-mono text-[9px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                      Before
                    </div>
                    <div className="mt-1 text-[13px] text-[#1a1a1a]/75">
                      {t.before[0]} at <span className="font-medium text-[#1a1a1a]">{t.before[1]}</span>
                    </div>
                  </div>
                  <div className="my-3 h-px bg-black/8" />
                  <div>
                    <div className="font-mono text-[9px] uppercase tracking-[0.28em] text-[#1a1a1a]/40">
                      During
                    </div>
                    <div className="mt-1 text-[13px] text-[#1a1a1a]/85">{t.during}</div>
                  </div>
                  <div className="my-3 h-px bg-black/8" />
                  <div>
                    <div className="font-mono text-[9px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                      After
                    </div>
                    <div className="mt-1 text-[13px] font-semibold text-[#1a1a1a]">
                      {t.after[0]} at <span style={{ color }}>{t.after[1]}</span>
                    </div>
                  </div>
                </div>
              </motion.article>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ─── The Model + OutClass ─── */
function Model() {
  return (
    <section className="border-t border-black/10 bg-white px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="The model"
          title={
            <>
              Three forces that make{" "}
              <span className="italic mu-gradient-text">MU different.</span>
            </>
          }
        />

        <div className="mt-10 grid gap-4 md:grid-cols-3">
          {MODEL.map((c, i) => (
            <div key={c.t} className="rounded-2xl border border-black/8 bg-white p-7">
              <div className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                <span
                  className="inline-block h-1.5 w-6"
                  style={{ backgroundColor: ACCENT[i % ACCENT.length] }}
                />
                {c.eb}
              </div>
              <h3 className="font-display mt-4 text-[clamp(1.3rem,2.2vw,1.7rem)] font-medium leading-tight tracking-tight">
                {c.t}
              </h3>
              <p className="font-display mt-3 text-[15px] leading-relaxed text-[#1a1a1a]/75">
                {c.b}
              </p>
            </div>
          ))}
        </div>

        <div className="mt-10 grid gap-4 md:grid-cols-2">
          {OUTCLASS.map((c, i) => (
            <div
              key={c.t}
              className="flex flex-col gap-5 border-l-4 bg-[#fafaf7] p-7 md:flex-row md:items-end"
              style={{ borderLeftColor: ACCENT[i % ACCENT.length] }}
            >
              <div className="md:w-1/2">
                <Eyebrow>{c.eb}</Eyebrow>
                <h3 className="font-display mt-3 text-[22px] font-medium leading-tight tracking-tight">
                  {c.t}
                </h3>
                <p className="mt-3 text-[14px] leading-relaxed text-[#1a1a1a]/70">{c.b}</p>
              </div>
              <div className="md:w-1/2 md:text-right">
                <div className="font-display text-[clamp(2rem,4vw,3rem)] font-thin leading-none tracking-[-0.04em]">
                  {c.s}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── Curriculum ─── */
function Curriculum() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <section className="border-t border-black/10 bg-[#fafaf7] px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="InClass curriculum"
          title={
            <>
              Learn it in class.{" "}
              <span className="italic mu-gradient-text">Prove it outside.</span>
            </>
          }
          lede="Five domains. 200+ practitioners. Every module designed and delivered with the CEOs, founders, and operators who run the industry today."
        />

        <div className="mt-10 divide-y divide-black/10 border-t border-b border-black/10">
          {CURRICULUM_DOMAINS.map((d, i) => {
            const isOpen = open === i;
            const color = ACCENT[i % ACCENT.length];
            return (
              <div key={d.title}>
                <button
                  onClick={() => setOpen(isOpen ? null : i)}
                  className="group flex w-full items-center justify-between gap-6 py-6 text-left"
                >
                  <div className="flex items-baseline gap-6">
                    <span className="font-mono text-[12px] font-medium tabular-nums text-[#1a1a1a]/55">
                      0{i + 1}
                    </span>
                    <h3 className="font-display text-[clamp(1.2rem,2.4vw,1.8rem)] font-medium leading-tight tracking-tight transition-colors group-hover:opacity-80">
                      {d.title}
                    </h3>
                  </div>
                  <span
                    className="font-display text-[26px] font-thin leading-none"
                    style={{ color }}
                  >
                    {isOpen ? "–" : "+"}
                  </span>
                </button>
                {isOpen && (
                  <motion.div
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-8 pb-8 md:grid-cols-[1fr_320px]"
                  >
                    <div>
                      <p className="font-display max-w-[60ch] text-[15px] leading-relaxed text-[#1a1a1a]/75">
                        {d.blurb}
                      </p>
                      <ul className="mt-5 space-y-2.5 text-[14px] leading-[1.65] text-[#1a1a1a]/85">
                        {d.bullets.map((b) => (
                          <li key={b} className="flex gap-3">
                            <span
                              className="mt-2 inline-block h-1 w-1 shrink-0"
                              style={{ backgroundColor: color }}
                            />
                            <span>{b}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div className="border border-black/10 bg-white p-5">
                      <div className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                        Faculty highlights
                      </div>
                      <p className="mt-3 text-[13px] leading-[1.65] text-[#1a1a1a]/85">
                        {d.facultyHighlight}
                      </p>
                    </div>
                  </motion.div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ─── 7 Programs ─── */
function Programs() {
  const [tab, setTab] = useState<Cluster>("All");
  const visible = tab === "All" ? PROGRAMS : PROGRAMS.filter((p) => p.cluster === tab);

  return (
    <section
      id="programs"
      className="border-t border-black/10 bg-white px-6 py-14 md:px-12 md:py-20"
    >
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="The 7 programmes"
          title={
            <>
              Pick the one that fits{" "}
              <span className="italic mu-gradient-text">your ambition.</span>
            </>
          }
        />

        <div className="mt-8 flex flex-wrap gap-2">
          {TABS.map((t) => {
            const on = tab === t;
            return (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`border px-4 py-2 font-mono text-[11px] uppercase tracking-[0.22em] transition ${
                  on
                    ? "border-[#1a1a1a] bg-[#1a1a1a] text-white"
                    : "border-black/15 text-[#1a1a1a]/70 hover:border-black/40"
                }`}
              >
                {t}
              </button>
            );
          })}
        </div>

        <div className="mt-8 grid gap-4 md:grid-cols-2">
          {visible.map((p, i) => {
            const color = ACCENT[i % ACCENT.length];
            return (
              <motion.article
                key={p.title}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
                className="flex flex-col border-l-4 border-black/8 bg-white p-7"
                style={{ borderLeftColor: color }}
              >
                <div className="self-start border border-black/10 px-2.5 py-1 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/70">
                  {p.tag}
                </div>
                <h3 className="font-display mt-5 text-[clamp(1.3rem,2.2vw,1.7rem)] font-medium leading-tight tracking-tight">
                  {p.title}
                </h3>
                <p className="font-display mt-3 text-[15px] italic text-[#1a1a1a]/80">
                  "{p.hook}"
                </p>
                <ul className="mt-5 space-y-2.5 text-[14px] leading-[1.65] text-[#1a1a1a]/75">
                  {p.points.map((pt) => (
                    <li key={pt} className="flex gap-3">
                      <span
                        className="mt-2 inline-block h-1 w-1 shrink-0"
                        style={{ backgroundColor: color }}
                      />
                      <span>{pt}</span>
                    </li>
                  ))}
                </ul>
                <a
                  href="#apply"
                  className="mt-6 font-mono text-[11px] uppercase tracking-[0.28em] text-[#1a1a1a] transition hover:opacity-60"
                >
                  {p.cta}
                </a>
              </motion.article>
            );
          })}
        </div>
      </div>
    </section>
  );
}

/* ─── Faculty + Cohort ─── */
function FacultyCohort() {
  return (
    <section className="border-t border-black/10 bg-[#fafaf7] px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2 md:gap-16">
        <div>
          <Eyebrow>Faculty</Eyebrow>
          <h2 className="font-display mt-3 max-w-[18ch] text-balance text-[clamp(1.6rem,3.6vw,2.6rem)] font-light leading-[1.05] tracking-tight">
            Taught by the people{" "}
            <span className="italic mu-gradient-text">running the industry.</span>
          </h2>

          <div className="mt-8 space-y-6">
            {FACULTY_SPLIT.map(([n, t, d], i) => (
              <div key={t} className="flex gap-6 border-b border-black/10 pb-6 last:border-0">
                <div
                  className="font-display w-24 shrink-0 text-[clamp(2rem,4vw,2.6rem)] font-thin leading-none tracking-[-0.04em]"
                  style={{ color: ACCENT[i] }}
                >
                  {n}
                </div>
                <div>
                  <div className="font-display text-[17px] font-medium text-[#1a1a1a]">{t}</div>
                  <div className="mt-1 text-[14px] text-[#1a1a1a]/65">{d}</div>
                </div>
              </div>
            ))}
          </div>

          <blockquote className="mt-8 border-l-2 pl-5" style={{ borderColor: ACCENT[1] }}>
            <p className="font-display text-[17px] italic leading-[1.6] text-[#1a1a1a]/90">
              "Masters' Union is doing something genuinely different. We've brought Kellogg
              students here two years in a row."
            </p>
            <footer className="mt-3 font-mono text-[10px] uppercase tracking-[0.25em] text-[#1a1a1a]/55">
              — Prof. Mohanbir Sawhney, Kellogg School of Management
            </footer>
          </blockquote>
        </div>

        <div className="self-start border border-black/10 bg-white p-8 md:p-10">
          <Eyebrow>Cohort profile</Eyebrow>
          <div className="mt-6 space-y-6">
            {COHORT.map(([n, l]) => (
              <div key={l} className="border-b border-black/8 pb-5 last:border-0">
                <div className="font-display text-[clamp(2rem,3.6vw,2.6rem)] font-thin leading-none tracking-[-0.03em]">
                  {n}
                </div>
                <div className="mt-2 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
                  {l}
                </div>
              </div>
            ))}
          </div>
          <div className="mt-7 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
            Backgrounds
          </div>
          <p className="mt-2 text-[15px] text-[#1a1a1a]/85">
            Consulting · Finance · Tech · Startups · Family Business · FMCG · Media
          </p>
          <p className="font-display mt-6 text-[14px] italic text-[#1a1a1a]/70">
            "Small cohort. High bar. Everyone here chose MU over conventional options."
          </p>
        </div>
      </div>
    </section>
  );
}

/* ─── Immersions ─── */
function Immersions() {
  return (
    <section className="border-t border-black/10 bg-white px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Immersions"
          title={
            <>
              Learn in boardrooms, on factory floors,{" "}
              <span className="italic mu-gradient-text">and across continents.</span>
            </>
          }
          lede="From INSEAD Paris to Chandni Chowk in Delhi — our immersions take you inside real boardrooms, factory floors, and startup ecosystems across the world and across India."
        />

        <div className="mt-10 grid grid-cols-2 gap-px border border-black/10 bg-black/10 lg:grid-cols-4">
          {IMMERSION_STATS.map(([n, t, s]) => (
            <div key={t} className="bg-white px-5 py-5">
              <div className="font-display text-[clamp(1.8rem,3vw,2.4rem)] font-thin leading-none tracking-[-0.03em]">
                {n}
              </div>
              <div className="mt-3 text-[13px] font-medium text-[#1a1a1a]">{t}</div>
              <div className="mt-1 text-[12px] text-[#1a1a1a]/55">{s}</div>
            </div>
          ))}
        </div>

        <div className="mt-8 grid gap-4 md:grid-cols-3">
          {IMMERSIONS.map((c, i) => (
            <div key={c.t} className="rounded-2xl border border-black/8 bg-[#fafaf7] p-7">
              <div className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                <span
                  className="inline-block h-1.5 w-6"
                  style={{ backgroundColor: ACCENT[i % ACCENT.length] }}
                />
                {c.eb}
              </div>
              <h3 className="font-display mt-4 text-[22px] font-medium leading-tight tracking-tight">
                {c.t}
              </h3>
              <p className="font-display mt-3 text-[15px] leading-relaxed text-[#1a1a1a]/75">
                {c.b}
              </p>
              {c.meta && (
                <p className="mt-5 border-t border-black/10 pt-4 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
                  {c.meta}
                </p>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── Entrepreneurship ─── */
function Entrepreneurship() {
  return (
    <section className="border-t border-black/10 bg-[#fafaf7] px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Entrepreneurship"
          title={
            <>
              Where founders are built,{" "}
              <span className="italic mu-gradient-text">not just funded.</span>
            </>
          }
          lede="From hostel-room ideas to funded ventures — our founders ship products, raise capital, and scale while still on campus."
        />

        <div className="mt-10 grid grid-cols-3 gap-px border border-black/10 bg-black/10 lg:grid-cols-5">
          {FUND_STATS.map(([n, l]) => (
            <div key={l} className="bg-white px-4 py-5">
              <div className="font-display text-[clamp(1.6rem,2.6vw,2.1rem)] font-thin leading-none tracking-[-0.03em]">
                {n}
              </div>
              <div className="mt-2 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
                {l}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12">
          <div className="mb-5 flex items-center gap-3">
            <span className="h-px w-8" style={{ background: ACCENT[0] }} />
            <span className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/70">
              Startup portfolio
            </span>
            <span className="h-px flex-1 bg-black/10" />
          </div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {STARTUPS.map(([n, t, tag], i) => (
              <div
                key={n}
                className="border border-black/8 border-t-2 bg-white p-5"
                style={{ borderTopColor: ACCENT[i % ACCENT.length] }}
              >
                <div className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
                  {tag}
                </div>
                <h4 className="font-display mt-2 text-[20px] font-medium leading-tight tracking-tight">
                  {n}
                </h4>
                <p className="mt-2 text-[13px] leading-snug text-[#1a1a1a]/70">{t}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-12">
          <div className="mb-5 flex items-center gap-3">
            <span className="h-px w-8" style={{ background: ACCENT[2] }} />
            <span className="font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/70">
              Featured on Shark Tank India
            </span>
            <span className="h-px flex-1 bg-black/10" />
          </div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {SHARK_TANK.map(([n, s, f, d]) => (
              <div key={n} className="border border-black/10 bg-white p-5">
                <span
                  className="inline-block px-2 py-1 font-mono text-[9px] uppercase tracking-[0.22em] text-[#1a1a1a]"
                  style={{ background: `${ACCENT[1]}33` }}
                >
                  {s}
                </span>
                <h4 className="font-display mt-3 text-[18px] font-medium leading-tight">{n}</h4>
                <p className="mt-1.5 text-[12px] leading-snug text-[#1a1a1a]/65">{d}</p>
                <div className="mt-3 text-[12px] font-medium text-[#1a1a1a]/85">{f}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

/* ─── Admissions ─── */
function Admissions() {
  const [showMuBaat, setShowMuBaat] = useState(false);
  return (
    <section className="border-t border-black/10 bg-white px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Admissions"
          title={
            <>
              Your <span className="italic mu-gradient-text">path in.</span>
            </>
          }
          lede={
            <>
              No CAT/GMAT required. We have the{" "}
              <button
                onClick={() => setShowMuBaat((s) => !s)}
                className="underline decoration-2 underline-offset-2 hover:opacity-70"
                style={{ textDecorationColor: ACCENT[2] }}
              >
                MU-BAAT
              </button>{" "}
              — our own aptitude test that evaluates ambition, grit, and the drive to build.
            </>
          }
        />

        <div className="mt-10 grid grid-cols-5 gap-px border border-black/10 bg-black/10">
          {ADMISSIONS_STEPS.map(([n, t], i) => (
            <div key={n} className="bg-white px-3 py-5 sm:px-5">
              <div
                className="font-display text-[clamp(1.5rem,2.4vw,2rem)] font-thin leading-none tracking-[-0.04em] tabular-nums"
                style={{ color: ACCENT[i % ACCENT.length] }}
              >
                {n}
              </div>
              <div className="mt-2 text-[12px] font-medium text-[#1a1a1a] sm:text-[14px]">{t}</div>
            </div>
          ))}
        </div>

        {showMuBaat && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="mt-6 border border-black/10 bg-[#fafaf7] p-6 md:p-8"
          >
            <div className="mb-4 flex items-baseline justify-between">
              <div>
                <h4 className="font-display text-[20px] font-medium">MU-BAAT</h4>
                <p className="mt-1 font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55">
                  Masters' Union Business Aptitude & Admission Test
                </p>
              </div>
              <button
                onClick={() => setShowMuBaat(false)}
                className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#1a1a1a]/55 hover:text-[#1a1a1a]"
              >
                Close
              </button>
            </div>
            <p
              className="font-display max-w-3xl border-l-2 pl-4 text-[15px] italic leading-[1.7] text-[#1a1a1a]/85"
              style={{ borderColor: ACCENT[2] }}
            >
              You record your responses online — no prior preparation needed. Think of it as a
              conversation with the Masters' Union team that helps us understand you beyond your
              résumé.
            </p>
            <div className="mt-6 grid gap-6 md:grid-cols-3">
              <div>
                <div className="font-mono text-[10px] uppercase tracking-[0.24em] text-[#1a1a1a]/55">
                  Evaluates
                </div>
                <ul className="mt-2 space-y-1.5 text-[13px] text-[#1a1a1a]/80">
                  <li>· Communication & business aptitude</li>
                  <li>· Clarity of thought & idea structuring</li>
                  <li>· Creative & analytical thinking</li>
                </ul>
              </div>
              <div>
                <div className="font-mono text-[10px] uppercase tracking-[0.24em] text-[#1a1a1a]/55">
                  Format
                </div>
                <div className="mt-2 space-y-1 text-[13px] text-[#1a1a1a]/80">
                  <div>
                    Duration: <span className="font-semibold">45–60 min</span>
                  </div>
                  <div>
                    Structure: <span className="font-semibold">9 questions, 5 sections</span>
                  </div>
                  <div className="mt-2 text-[12px] text-[#1a1a1a]/55">
                    The MU-BAAT link is shared the day after your application deadline.
                  </div>
                </div>
              </div>
              <div>
                <div className="font-mono text-[10px] uppercase tracking-[0.24em] text-[#1a1a1a]/55">
                  Sample question
                </div>
                <p className="font-display mt-2 text-[13px] italic leading-relaxed text-[#1a1a1a]/80">
                  "A D2C skincare brand increased ad spend, but average order value fell 20%,
                  while new users grew. What happened?"
                </p>
              </div>
            </div>
          </motion.div>
        )}

        <div className="mt-8 flex flex-col items-start justify-between gap-4 border border-black/10 bg-[#fafaf7] p-5 sm:flex-row sm:items-center">
          <p className="text-[14px] text-[#1a1a1a]/75">
            Don't miss your chance to join the next cohort. Apply before{" "}
            <strong style={{ color: ACCENT[0] }}>3rd May 2026</strong>.
          </p>
          <a
            href="#apply"
            className="inline-flex items-center bg-[#1a1a1a] px-5 py-3 font-mono text-[11px] uppercase tracking-[0.28em] text-white transition hover:bg-[#1a1a1a]/85"
          >
            Apply Now →
          </a>
        </div>
      </div>
    </section>
  );
}

/* ─── Fees ─── */
function Fees() {
  return (
    <section className="border-t border-black/10 bg-[#fafaf7] px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <SectionHead
          eb="Investment & financial support"
          title={
            <>
              An investment{" "}
              <span className="italic mu-gradient-text">in your future.</span>
            </>
          }
          lede="Masters' Union believes financial constraints should never stand between talent and transformation. Multiple scholarship and financing options ensure accessibility."
        />

        <div className="mt-10 grid gap-4 md:grid-cols-3">
          {FEES.map((h, i) => (
            <div key={h.t} className="rounded-2xl border border-black/8 bg-white p-7">
              <div
                aria-hidden
                className="h-px w-10"
                style={{ backgroundColor: ACCENT[i % ACCENT.length] }}
              />
              <h3 className="font-display mt-4 text-[clamp(1.2rem,2vw,1.5rem)] font-medium leading-tight tracking-tight">
                {h.t}
              </h3>
              <p className="font-display mt-3 text-[15px] leading-relaxed text-[#1a1a1a]/75">
                {h.b}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── FAQ ─── */
function FAQ() {
  const [openFaq, setOpenFaq] = useState<string | null>(null);
  return (
    <section className="border-t border-black/10 bg-white px-6 py-14 md:px-12 md:py-20">
      <div className="mx-auto max-w-[1100px]">
        <Eyebrow>FAQ</Eyebrow>
        <h2 className="font-display mt-3 text-[clamp(1.6rem,3.6vw,2.8rem)] font-light leading-[1.05] tracking-tight">
          Questions before <span className="italic mu-gradient-text">you apply.</span>
        </h2>

        <div className="mt-10 grid gap-x-12 gap-y-2 md:grid-cols-2">
          {[
            { title: "Admissions & Programme", items: FAQS_LEFT, prefix: "a" },
            { title: "Fees & Financial Support", items: FAQS_RIGHT, prefix: "f" },
          ].map((col) => (
            <div key={col.title}>
              <div className="mb-2 border-b border-black/15 pb-3 font-mono text-[10px] uppercase tracking-[0.28em] text-[#1a1a1a]/55">
                {col.title}
              </div>
              {col.items.map((f, i) => {
                const key = `${col.prefix}-${i}`;
                const open = openFaq === key;
                return (
                  <div key={key} className="border-b border-black/10">
                    <button
                      onClick={() => setOpenFaq(open ? null : key)}
                      className="flex w-full items-start justify-between gap-4 py-4 text-left"
                    >
                      <span className="text-[14px] font-medium text-[#1a1a1a]">{f.q}</span>
                      <span
                        className="font-display shrink-0 text-[20px] font-thin leading-none"
                        style={{ color: ACCENT[i % ACCENT.length] }}
                      >
                        {open ? "–" : "+"}
                      </span>
                    </button>
                    {open && (
                      <p className="font-display pb-5 text-[14px] leading-[1.7] text-[#1a1a1a]/70">
                        {f.a}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── Final CTA ─── */
function CTA() {
  return (
    <section
      id="apply"
      className="border-t border-black/10 bg-[#1a1a1a] px-6 py-14 text-white md:px-12 md:py-20"
    >
      <div className="mx-auto max-w-5xl text-center">
        <p className="font-mono text-[10px] uppercase tracking-[0.3em] text-white/55">
          Admissions
        </p>
        <h2 className="font-display mt-4 text-balance text-[clamp(1.7rem,5vw,3.8rem)] font-light leading-[0.98] tracking-tight">
          The next cohort is forming. <br />
          <span className="italic mu-gradient-text">Your seat isn't reserved.</span>
        </h2>
        <p className="mt-4 font-mono text-[11px] uppercase tracking-[0.3em] text-white/55">
          June 2026 · ~120 Seats · Round 3 closing soon
        </p>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <a
            href="https://mastersunion.org/pgp-tbm-applynow"
            target="_blank"
            rel="noopener noreferrer"
            className="border-[1.5px] border-transparent bg-white px-6 py-4 font-mono text-[11px] uppercase tracking-[0.3em] text-[#1a1a1a] transition hover:bg-white/90"
            style={{
              borderImage:
                "linear-gradient(91deg, #39B5D7 -6%, #F7D544 47%, #E38330 100%) 1",
            }}
          >
            Apply Now →
          </a>
          <a
            href="#"
            className="border border-white/25 px-6 py-4 font-mono text-[11px] uppercase tracking-[0.3em] text-white transition hover:border-white/60"
          >
            Book an Admissions Call
          </a>
        </div>
        <div className="mx-auto mt-10 max-w-5xl border-t border-white/10 pt-6 text-center font-mono text-[10px] uppercase tracking-[0.25em] text-white/40">
          EFMD Accredited · AACSB Member · 148 Recruiters · ₹61.98L Highest CTC
        </div>
      </div>
    </section>
  );
}
