import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";

export const Route = createFileRoute("/pg-programs")({
  head: () => ({
    meta: [
      { title: "Postgraduate Programs — Masters' Union" },
      {
        name: "description",
        content:
          "The MBA that pays for itself before you graduate. ₹33.39L average CTC, 3.03x salary jump, 148 recruiters.",
      },
      { property: "og:title", content: "Postgraduate Programs — Masters' Union" },
      {
        property: "og:description",
        content: "Real revenue, real fund, real placements. Bain, Google, Goldman.",
      },
    ],
  }),
  component: PgProgramsPage,
});

const display = { fontFamily: "'Playfair Display', serif" };
const body = { fontFamily: "'Plus Jakarta Sans', sans-serif" };
const dotGrid = {
  backgroundImage:
    "radial-gradient(circle, rgba(255,255,255,0.03) 1px, transparent 1px)",
  backgroundSize: "28px 28px",
};

type Cluster = "All" | "Business" | "Technology & Design" | "Specialised";

type Program = {
  cluster: Exclude<Cluster, "All">;
  title: string;
  tag: string;
  hook: string;
  points: string[];
  cta: string;
};

const PROGRAMS: Program[] = [
  {
    cluster: "Business",
    title: "PGP in Technology & Business Management",
    tag: "Flagship · 15 Months",
    hook: "For those who want to run companies, not just work at them.",
    points: [
      "Grades based on revenue, users & NPS — not exams",
      "Run a real e-commerce business (Cohort '25: ₹3.38 Cr revenue)",
      "Manage a ₹5 Cr student investment fund",
      "46M+ content views generated by Cohort 6",
      "Placements: Bain, BCG, McKinsey, Google, Zepto, Axis Capital",
    ],
    cta: "Explore TBM →",
  },
  {
    cluster: "Business",
    title: "PGP in Technology & Business Management — Young Leaders Cohort",
    tag: "Accelerated",
    hook: "For exceptional graduates who don't want to wait two years to lead.",
    points: [
      "Compressed, high-intensity TBM curriculum",
      "Same OutClass experiences — Dropshipping Fair, Investment Fund, Creator Challenge",
      "Designed for 0–2 years experience",
    ],
    cta: "Explore YLC →",
  },
  {
    cluster: "Business",
    title: "PGP in Human Resources & Organisation Strategy",
    tag: "Full Time",
    hook: "For those who want to build and run the organisations others work at.",
    points: [
      "People strategy, org design, culture, and talent systems",
      "OutClass: live org audits with real companies",
      "Career paths: CHRO track, people ops, consulting, founder's office",
    ],
    cta: "Explore HR & Org Strategy →",
  },
  {
    cluster: "Business",
    title: "PGP in Sustainability & Business Management",
    tag: "Full Time",
    hook: "For those building businesses that last beyond a balance sheet.",
    points: [
      "ESG strategy, climate economics, sustainable supply chains",
      "OutClass: live sustainability audits with corporate partners",
      "Career paths: ESG consulting, impact investing, sustainability leadership",
    ],
    cta: "Explore Sustainability →",
  },
  {
    cluster: "Technology & Design",
    title: "PGP in Applied AI & Agentic Systems",
    tag: "Full Time",
    hook: "For those who want to build with AI, not just talk about it.",
    points: [
      "LLMs, agentic workflows, real deployment",
      "OutClass: ship working AI products — evaluated on adoption, not theory",
      "Career paths: AI product, AI consulting, founding engineer, AI strategy",
    ],
    cta: "Explore Applied AI →",
  },
  {
    cluster: "Technology & Design",
    title: "PGP in UI/UX & AI Product Design",
    tag: "Full Time",
    hook: "For those who design what millions of people actually use.",
    points: [
      "Product design, AI-native UX, design systems",
      "Studio model: critique-based, not lecture-based",
      "Career paths: Product designer, UX lead, design founder",
    ],
    cta: "Explore UI/UX & Product Design →",
  },
  {
    cluster: "Specialised",
    title: "PGP in Sports Management & Gaming",
    tag: "Full Time",
    hook: "For those building the business of sport and interactive entertainment.",
    points: [
      "Sports business, franchise management, gaming ecosystems, media rights",
      "OutClass: live projects with franchises, esports orgs, gaming companies",
      "Career paths: franchise ops, esports, sports media, gaming product",
    ],
    cta: "Explore Sports & Gaming →",
  },
];

const TABS: Cluster[] = ["All", "Business", "Technology & Design", "Specialised"];

const STATS = [
  ["₹33.39L", "Average CTC"],
  ["₹61.98L", "Highest CTC"],
  ["3.03x", "Salary Jump from Pre-MBA"],
  ["148", "Recruiters"],
  ["35+", "International Offers"],
  ["10–20%", "Annual Salary Growth"],
];

const ALUMNI = [
  ["Jeneesha Singh", "Associate Consultant, Bain & Company (Co'23)"],
  ["Daniel Paul Nath", "Growth Strategist, Google Dublin (Co'24)"],
  ["Dharmil Bavishi", "Founder, Bullspree · Shark Tank Season 2 (Co'21)"],
  ["Prashasti Singh", "Consultant, McKinsey (Co'23)"],
  ["Gautam Marwah", "Chief of Staff, Kae Capital (Co'24)"],
  ["Radika Agarwal", "Investment Analyst, Good Capital (Co'24)"],
];

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={body}
      className="text-[11px] font-medium uppercase tracking-[0.14em] text-[#F4C641]"
    >
      {children}
    </div>
  );
}

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <div
      className={`bg-[#161616] border border-white/[0.07] rounded-[2px] transition-colors duration-200 hover:border-[#F4C641]/30 ${className}`}
    >
      {children}
    </div>
  );
}

function PgProgramsPage() {
  const [tab, setTab] = useState<Cluster>("All");
  const visible = tab === "All" ? PROGRAMS : PROGRAMS.filter((p) => p.cluster === tab);

  return (
    <div className="min-h-screen bg-[#101010] text-white scroll-smooth" style={body}>
      {/* HERO */}
      <section className="relative" style={dotGrid}>
        <div className="mx-auto max-w-[1200px] px-6 pt-32 pb-24 md:pt-40 md:pb-32">
          <Eyebrow>Postgraduate Programmes</Eyebrow>
          <h1
            style={display}
            className="mt-6 text-[40px] md:text-[72px] leading-[1.05] font-normal text-white max-w-[18ch]"
          >
            The MBA That Pays for Itself Before You Graduate.
          </h1>
          <p className="mt-8 text-[18px] leading-[1.7] text-[#6B6B6B] max-w-[560px]">
            Masters' Union PG students generate real revenue, manage a ₹5 Cr investment fund,
            build personal brands with 46M+ reach, and step into roles at Bain, Google, and
            Goldman — with a 3.03x salary jump.
          </p>
          <div className="mt-10 flex flex-wrap gap-3">
            <a
              href="#apply"
              className="inline-flex items-center px-6 py-3.5 bg-[#F4C641] text-[#101010] text-[14px] font-semibold rounded-none hover:bg-[#F4C641]/90 transition-colors"
            >
              Apply for PG Programs
            </a>
            <a
              href="#"
              className="inline-flex items-center px-6 py-3.5 border border-white/20 text-white text-[14px] font-semibold rounded-none hover:border-white/40 transition-colors"
            >
              Download Brochure
            </a>
          </div>
        </div>
        {/* Signature hinge */}
        <div className="h-px w-full bg-[#F4C641]" />
      </section>

      {/* OUTCOMES */}
      <section className="bg-[#101010]">
        <div className="mx-auto max-w-[1200px] px-6 py-16 md:py-[120px]">
          <Eyebrow>Outcomes</Eyebrow>
          <div className="mt-12 grid grid-cols-2 md:grid-cols-3 gap-y-12 gap-x-8">
            {STATS.map(([n, l]) => (
              <div key={l}>
                <div
                  style={body}
                  className="text-[36px] md:text-[48px] font-bold text-[#F4C641] leading-none"
                >
                  {n}
                </div>
                <div className="mt-3 text-[13px] uppercase tracking-[0.14em] text-[#6B6B6B]">
                  {l}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-20 grid md:grid-cols-2 gap-12 md:gap-16">
            <div>
              <Eyebrow>Where They Go</Eyebrow>
              <div className="mt-6 space-y-5 text-[15px] leading-[1.7] text-white/85">
                <p>
                  <span className="text-[#6B6B6B] block text-[12px] uppercase tracking-[0.14em] mb-1">
                    Consulting
                  </span>
                  Bain · BCG · McKinsey · Accenture Strategy · EY-Parthenon · Kearney · PwC
                </p>
                <p>
                  <span className="text-[#6B6B6B] block text-[12px] uppercase tracking-[0.14em] mb-1">
                    Finance / VC
                  </span>
                  Axis Capital · Kotak IB · InnoVen Capital · WaterBridge Ventures · Avaana Capital
                </p>
                <p>
                  <span className="text-[#6B6B6B] block text-[12px] uppercase tracking-[0.14em] mb-1">
                    Tech
                  </span>
                  Google · Microsoft · Razorpay · Zepto · Zomato · MakeMyTrip
                </p>
                <p>
                  <span className="text-[#6B6B6B] block text-[12px] uppercase tracking-[0.14em] mb-1">
                    International
                  </span>
                  Google Dublin · Careem Dubai · Talabat Dubai · Avirom Capital US
                </p>
              </div>
            </div>
            <div>
              <Eyebrow>Alumni</Eyebrow>
              <ul className="mt-6 divide-y divide-white/[0.07]">
                {ALUMNI.map(([n, r]) => (
                  <li key={n} className="py-4">
                    <div className="text-white text-[15px] font-medium">{n}</div>
                    <div className="text-[13px] text-[#6B6B6B] mt-1">{r}</div>
                  </li>
                ))}
              </ul>
              <p className="mt-6 text-[13px] text-[#6B6B6B]">
                12% of every cohort goes directly into VC and investment roles.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CURRICULUM & ARCHITECTURE */}
      <section className="bg-[#101010] border-t border-white/[0.07]">
        <div className="mx-auto max-w-[1200px] px-6 py-16 md:py-[120px]">
          <Eyebrow>The Model</Eyebrow>
          <h2
            style={display}
            className="mt-6 text-[28px] md:text-[40px] font-normal text-white max-w-[22ch]"
          >
            Three Forces That Make MU Different.
          </h2>

          <div className="mt-14 grid md:grid-cols-3 gap-6">
            {[
              {
                eb: "InClass",
                t: "Faculty Who've Done It",
                b: "30% professors from Harvard, Stanford, Wharton, Kellogg. 50% CEOs and operators. 20% PhD faculty. Every session is a real decision, not a case study.",
              },
              {
                eb: "OutClass",
                t: "Your Grade Is Your Revenue",
                b: "No exams. Grades based on real products, real revenue, real NPS. You run businesses. You manage a fund. You build brands. You pitch to VCs.",
              },
              {
                eb: "Immersions",
                t: "India & The World",
                b: "Full-term Bharat Immersion: 7,000 km, 8 hubs, 20+ cities, 40+ CXO sessions. Global: 8 immersions across 7 countries — INSEAD, Boeing, BMW, London finance desks.",
              },
            ].map((c) => (
              <Card key={c.t} className="p-8">
                <Eyebrow>{c.eb}</Eyebrow>
                <h3
                  style={display}
                  className="mt-4 text-[24px] leading-[1.2] text-white font-normal"
                >
                  {c.t}
                </h3>
                <p className="mt-4 text-[15px] leading-[1.7] text-[#6B6B6B]">{c.b}</p>
              </Card>
            ))}
          </div>

          {/* OutClass experiences 2x2 */}
          <div className="mt-6 grid md:grid-cols-2 gap-6">
            {[
              {
                t: "Dropshipping Fair",
                term: "Term 1",
                s: "₹3.38 Cr",
                b: "50 teams. Real products. Real customers. Cohort '25 total revenue.",
              },
              {
                t: "Content Creator Challenge",
                term: "Term 2",
                s: "46M+",
                b: "120+ creators. ₹10L+ prize pool. 80+ live brand assets delivered to real D2C brands in 24 hours.",
              },
              {
                t: "Student Investment Fund",
                term: "",
                s: "₹5 Cr",
                b: "Real corpus. Beaten public markets by 20–25% consistently. 5+ startup co-investments alongside VCs.",
              },
              {
                t: "Venture Initiation Programme",
                term: "",
                s: "₹593 Cr",
                b: "Combined portfolio valuation. ₹25.24 Cr raised. 6 Shark Tank India appearances. 100+ VCs at Demo Day.",
              },
            ].map((c) => (
              <Card key={c.t} className="p-8 flex flex-col md:flex-row gap-6 md:items-end">
                <div className="md:w-1/2">
                  <Eyebrow>{c.term || "OutClass"}</Eyebrow>
                  <h3
                    style={display}
                    className="mt-3 text-[22px] leading-[1.2] text-white font-normal"
                  >
                    {c.t}
                  </h3>
                  <p className="mt-3 text-[14px] leading-[1.7] text-[#6B6B6B]">{c.b}</p>
                </div>
                <div className="md:w-1/2 md:text-right">
                  <div
                    style={body}
                    className="text-[40px] md:text-[48px] font-bold text-[#F4C641] leading-none"
                  >
                    {c.s}
                  </div>
                </div>
              </Card>
            ))}
          </div>

          {/* PROGRAMS */}
          <div className="mt-24">
            <Eyebrow>The 7 Programs</Eyebrow>
            <div className="mt-6 flex flex-wrap gap-2">
              {TABS.map((t) => {
                const active = tab === t;
                return (
                  <button
                    key={t}
                    onClick={() => setTab(t)}
                    className={`px-4 py-2 text-[12px] uppercase tracking-[0.14em] border rounded-none transition-colors duration-150 ${
                      active
                        ? "bg-[#F4C641] text-[#101010] border-[#F4C641]"
                        : "border-white/15 text-white/70 hover:border-white/40 hover:text-white"
                    }`}
                  >
                    {t}
                  </button>
                );
              })}
            </div>

            <div className="mt-10 grid md:grid-cols-2 gap-6 transition-opacity duration-150">
              {visible.map((p) => (
                <Card key={p.title} className="p-8 flex flex-col">
                  <div className="inline-flex self-start px-2.5 py-1 border border-white/15 text-[11px] uppercase tracking-[0.14em] text-white/70">
                    {p.tag}
                  </div>
                  <h3
                    style={display}
                    className="mt-5 text-[24px] leading-[1.2] text-white font-normal"
                  >
                    {p.title}
                  </h3>
                  <p className="mt-3 text-[15px] italic text-white/80">"{p.hook}"</p>
                  <ul className="mt-5 space-y-2.5 text-[14px] text-[#6B6B6B] leading-[1.65]">
                    {p.points.map((pt) => (
                      <li key={pt} className="flex gap-3">
                        <span className="mt-2 inline-block w-1 h-1 bg-[#F4C641] shrink-0" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                  <a
                    href="#"
                    className="mt-6 text-[13px] uppercase tracking-[0.14em] text-[#F4C641] hover:text-white transition-colors"
                  >
                    {p.cta}
                  </a>
                </Card>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FACULTY & COHORT */}
      <section className="bg-[#101010] border-t border-white/[0.07]">
        <div className="mx-auto max-w-[1200px] px-6 py-16 md:py-[120px] grid md:grid-cols-2 gap-12 md:gap-16">
          <div>
            <Eyebrow>Faculty</Eyebrow>
            <h2
              style={display}
              className="mt-6 text-[28px] md:text-[40px] leading-[1.15] font-normal text-white"
            >
              Taught by the People Running the Industry.
            </h2>
            <div className="mt-10 space-y-8">
              {[
                ["50%", "Industry Practitioners.", "CEOs, founders, operators."],
                [
                  "30%",
                  "Full-Time Faculty.",
                  "PhD educators from IIM Calcutta, Bangalore, Ahmedabad.",
                ],
                [
                  "20%",
                  "Visiting Faculty.",
                  "Harvard, Stanford, Wharton, Kellogg, Cornell, MIT Sloan, Imperial, Cambridge.",
                ],
              ].map(([n, t, d]) => (
                <div key={t} className="flex gap-6 border-b border-white/[0.07] pb-6">
                  <div
                    style={body}
                    className="text-[36px] font-bold text-[#F4C641] leading-none w-24 shrink-0"
                  >
                    {n}
                  </div>
                  <div>
                    <div className="text-white text-[16px] font-medium">{t}</div>
                    <div className="text-[14px] text-[#6B6B6B] mt-1">{d}</div>
                  </div>
                </div>
              ))}
            </div>
            <blockquote className="mt-10 border-l-2 border-[#F4C641] pl-5">
              <p className="text-[17px] leading-[1.6] text-white/90 italic" style={display}>
                "Masters' Union is doing something genuinely different. We've brought Kellogg
                students here two years in a row."
              </p>
              <footer className="mt-3 text-[13px] text-[#6B6B6B]">
                — Prof. Mohanbir Sawhney, Kellogg School of Management
              </footer>
            </blockquote>
          </div>

          {/* COHORT (light) */}
          <div className="bg-[#F1F1F1] text-[#101010] p-10 rounded-[2px] self-start">
            <div className="text-[11px] font-medium uppercase tracking-[0.14em] text-[#101010]/70">
              Cohort Profile
            </div>
            <div className="mt-8 space-y-8">
              {[
                ["24.5 Years", "Avg Age"],
                ["3.7 Years", "Avg Work Experience"],
                ["31%", "Female Representation"],
              ].map(([n, l]) => (
                <div key={l} className="border-b border-black/10 pb-6 last:border-0">
                  <div style={body} className="text-[40px] font-bold leading-none">
                    {n}
                  </div>
                  <div className="mt-2 text-[12px] uppercase tracking-[0.14em] text-[#101010]/60">
                    {l}
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-8 text-[13px] uppercase tracking-[0.14em] text-[#101010]/60">
              Backgrounds
            </div>
            <p className="mt-2 text-[15px] text-[#101010]/85">
              Consulting · Finance · Tech · Startups · Family Business
            </p>
            <p className="mt-6 text-[14px] italic text-[#101010]/70">
              "Small cohort. High bar. Everyone here chose MU over conventional options."
            </p>
          </div>
        </div>
      </section>

      {/* IMMERSIONS */}
      <section className="bg-[#101010] border-t border-white/[0.07]">
        <div className="mx-auto max-w-[1200px] px-6 py-16 md:py-[120px]">
          <Eyebrow>Immersions</Eyebrow>
          <h2
            style={display}
            className="mt-6 text-[28px] md:text-[40px] leading-[1.15] font-normal text-white max-w-[22ch]"
          >
            Learn in Boardrooms, on Factory Floors, and Across Continents.
          </h2>
          <div className="mt-14 grid md:grid-cols-3 gap-6">
            {[
              {
                eb: "Campus",
                t: "DLF Cyberpark, Gurugram",
                b: "85% of Fortune 500 companies within 2 km. BCG, EY, Gartner are an elevator ride away. Recruiters don't fly in — they walk over.",
                meta: "",
              },
              {
                eb: "Bharat Immersion",
                t: "7,000 km Across India",
                b: "A full academic term on the road. Chandni Chowk → Dalal Street → Mundra Adani ports → Darjeeling tea estates.",
                meta: "8 Hubs · 20+ Cities · 40+ CXO Sessions · 50+ One-Day Immersions · Academic Credits",
              },
              {
                eb: "Global Immersion",
                t: "8 Immersions Across 7 Countries",
                b: "INSEAD Paris. London and New York finance desks. Boeing. BMW. SDA Bocconi.",
                meta: "Paris · Singapore · Boston · Milan · Berlin · London · Canada · Academic Credits",
              },
            ].map((c) => (
              <Card key={c.t} className="p-8">
                <Eyebrow>{c.eb}</Eyebrow>
                <h3
                  style={display}
                  className="mt-4 text-[22px] leading-[1.2] text-white font-normal"
                >
                  {c.t}
                </h3>
                <p className="mt-4 text-[15px] leading-[1.7] text-[#6B6B6B]">{c.b}</p>
                {c.meta && (
                  <p className="mt-5 pt-5 border-t border-white/[0.07] text-[12px] uppercase tracking-[0.14em] text-[#6B6B6B]">
                    {c.meta}
                  </p>
                )}
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section id="apply" className="bg-[#101010] border-t border-white/[0.07]" style={dotGrid}>
        <div className="mx-auto max-w-[1200px] px-6 py-16 md:py-[120px] text-center">
          <Eyebrow>Admissions</Eyebrow>
          <h2
            style={display}
            className="mt-6 text-[28px] md:text-[40px] leading-[1.15] font-normal text-white max-w-[26ch] mx-auto"
          >
            The Next Cohort Is Forming. Your Seat Isn't Reserved.
          </h2>
          <p className="mt-5 text-[16px] text-[#6B6B6B] max-w-[520px] mx-auto">
            Applications close when the cohort fills. Every batch has sold out.
          </p>
          <div className="mt-10 flex flex-wrap justify-center gap-3">
            <a
              href="#"
              className="inline-flex items-center px-6 py-3.5 bg-[#F4C641] text-[#101010] text-[14px] font-semibold rounded-none hover:bg-[#F4C641]/90 transition-colors"
            >
              Apply Now
            </a>
            <a
              href="#"
              className="inline-flex items-center px-6 py-3.5 border border-white/20 text-white text-[14px] font-semibold rounded-none hover:border-white/40 transition-colors"
            >
              Talk to Admissions
            </a>
          </div>
          <p className="mt-10 text-[12px] uppercase tracking-[0.14em] text-[#6B6B6B]">
            EFMD Accredited · AACSB Member · 148 Recruiters · ₹61.98L Highest CTC
          </p>
        </div>
      </section>
    </div>
  );
}
