import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/programs")({
  head: () => ({
    meta: [
      { title: "Postgraduate Programs — Masters' Union" },
      {
        name: "description",
        content:
          "Seven PG programs at Masters' Union. ₹33.39L avg CTC, 3.03x salary jump, 148 recruiters. Built for operators, founders and leaders.",
      },
      { property: "og:title", content: "Postgraduate Programs — Masters' Union" },
      {
        property: "og:description",
        content:
          "Seven tracks. One model. Avg CTC ₹33.39L · Highest ₹61.98L · 3.03x jump · 148 recruiters.",
      },
    ],
  }),
  component: ProgramsPage,
});

// ——————————————————————————————————————————————————————————
// Tokens
const INK = "#101010";
const PAPER = "#FFFFFF";
const CREAM = "#FAF8F4";
const RULE = "rgba(16,16,16,0.12)";
const MUTED = "rgba(16,16,16,0.62)";
const GRADIENT =
  "linear-gradient(90deg, #3EB6D3 0%, #F4C641 50%, #E58932 100%)";
const SERIF = "'Instrument Serif', 'Cormorant Garamond', Georgia, serif";
const SANS = "'Manrope', 'Inter', system-ui, sans-serif";
const MONO = "'JetBrains Mono', ui-monospace, Menlo, monospace";

// ——————————————————————————————————————————————————————————
// Data
type Program = {
  id: string;
  cluster: "business" | "tech" | "specialised";
  no: string;
  title: string;
  tag: string;
  hook: string;
  bullets: string[];
  cta: string;
};

const PROGRAMS: Program[] = [
  {
    id: "tbm",
    cluster: "business",
    no: "01",
    title: "PGP in Technology & Business Management",
    tag: "Flagship · 15 Months",
    hook: "For those who want to run companies, not just work at them.",
    bullets: [
      "Grades based on revenue, users & NPS — not exams",
      "Run a real e-commerce business (Cohort '25: ₹3.38 Cr revenue across 50 teams)",
      "Manage a ₹5 Cr student investment fund — beaten markets by 20–25%",
      "46M+ content views generated by Cohort 6",
      "Placements: Bain, BCG, McKinsey, Google, Zepto, Axis Capital",
    ],
    cta: "Explore TBM",
  },
  {
    id: "ylc",
    cluster: "business",
    no: "02",
    title: "PGP in Technology & Business Management (Young Leaders Cohort)",
    tag: "Accelerated · Cohort-Based",
    hook: "For exceptional graduates who don't want to wait two years to lead.",
    bullets: [
      "Compressed, high-intensity TBM curriculum",
      "Same OutClass experiences — Dropshipping Fair, Investment Fund, Creator Challenge",
      "Designed for 0–2 years experience",
      "Small batch, faster track, higher peer density",
    ],
    cta: "Explore YLC",
  },
  {
    id: "hr",
    cluster: "business",
    no: "03",
    title: "PGP in Human Resources & Organisation Strategy",
    tag: "Specialised · Full Time",
    hook: "For those who want to build and run the organisations others work at.",
    bullets: [
      "People strategy, org design, culture, and talent systems",
      "InClass with practitioners from India's top HR and people functions",
      "OutClass: live org audits, workforce design challenges with real companies",
      "Career paths: CHRO track, people ops, consulting, founder's office",
    ],
    cta: "Explore HR & Org Strategy",
  },
  {
    id: "sustainability",
    cluster: "business",
    no: "04",
    title: "PGP in Sustainability & Business Management",
    tag: "Specialised · Full Time",
    hook: "For those building businesses that last beyond a balance sheet.",
    bullets: [
      "ESG strategy, climate economics, sustainable supply chains",
      "OutClass: live sustainability audits with corporate partners",
      "Immersions: policy desks, green infrastructure, global sustainability hubs",
      "Career paths: ESG consulting, impact investing, sustainability leadership",
    ],
    cta: "Explore Sustainability",
  },
  {
    id: "ai",
    cluster: "tech",
    no: "05",
    title: "PGP in Applied AI & Agentic Systems",
    tag: "Technology · Full Time",
    hook: "For those who want to build with AI, not just talk about it.",
    bullets: [
      "Curriculum built around LLMs, agentic workflows, and real deployment",
      "OutClass: ship working AI products — evaluated on adoption and usage, not theory",
      "Faculty: practitioners building and deploying AI systems at scale",
      "Career paths: AI product, AI consulting, founding engineer, AI strategy",
    ],
    cta: "Explore Applied AI",
  },
  {
    id: "design",
    cluster: "tech",
    no: "06",
    title: "PGP in UI/UX & AI Product Design",
    tag: "Technology · Full Time",
    hook: "For those who design what millions of people actually use.",
    bullets: [
      "Product design, interaction design, AI-native UX, design systems",
      "OutClass: build and ship real products with real users",
      "Studio model: critique-based learning, not lecture-based",
      "Career paths: Product designer, UX lead, AI product, design founder",
    ],
    cta: "Explore UI/UX & Product Design",
  },
  {
    id: "sports",
    cluster: "specialised",
    no: "07",
    title: "PGP in Sports Management & Gaming",
    tag: "Specialised · Full Time",
    hook: "For those building the business of sport and interactive entertainment.",
    bullets: [
      "Sports business, franchise management, gaming ecosystems, media rights",
      "OutClass: live projects with sports franchises, gaming companies, esports orgs",
      "Immersions: backstage at India's biggest sporting and gaming events",
      "Career paths: franchise ops, esports, sports media, gaming product",
    ],
    cta: "Explore Sports & Gaming",
  },
];

const FILTERS: { id: "all" | Program["cluster"]; label: string }[] = [
  { id: "all", label: "All Programs" },
  { id: "business", label: "Business" },
  { id: "tech", label: "Technology & Design" },
  { id: "specialised", label: "Specialised" },
];

// ——————————————————————————————————————————————————————————
function ProgramsPage() {
  const [filter, setFilter] = useState<"all" | Program["cluster"]>("all");
  const visible = useMemo(
    () => (filter === "all" ? PROGRAMS : PROGRAMS.filter((p) => p.cluster === filter)),
    [filter],
  );

  return (
    <main
      style={{
        background: PAPER,
        color: INK,
        fontFamily: SANS,
      }}
      className="min-h-screen"
    >
      {/* Top bar */}
      <header
        className="sticky top-0 z-40 backdrop-blur-md"
        style={{
          background: "rgba(255,255,255,0.85)",
          borderBottom: `1px solid ${RULE}`,
        }}
      >
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-10">
          <Link
            to="/"
            className="text-[11px] uppercase tracking-[0.25em] opacity-80 hover:opacity-100"
            style={{ fontFamily: MONO }}
          >
            ← Masters&apos; Union
          </Link>
          <div
            className="hidden text-[11px] uppercase tracking-[0.25em] opacity-70 md:block"
            style={{ fontFamily: MONO }}
          >
            Postgraduate Programs · 2026
          </div>
          <a
            href="#apply"
            className="rounded-full px-4 py-2 text-[11px] uppercase tracking-[0.2em] text-white"
            style={{ background: INK, fontFamily: MONO }}
          >
            Apply
          </a>
        </div>
      </header>

      {/* SECTION 1 — HERO */}
      <section className="relative overflow-hidden">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-x-0 top-0 h-[60%] opacity-[0.08]"
          style={{ background: GRADIENT, filter: "blur(80px)" }}
        />
        <div className="relative mx-auto max-w-7xl px-5 pb-20 pt-20 md:px-10 md:pb-28 md:pt-28">
          <div
            className="text-[11px] uppercase tracking-[0.32em] opacity-70"
            style={{ fontFamily: MONO }}
          >
            Postgraduate · Cohort 2026
          </div>
          <h1
            className="mt-8 max-w-[18ch] text-balance text-[clamp(2.6rem,7.2vw,6.4rem)] font-normal leading-[0.96] tracking-[-0.02em]"
            style={{ fontFamily: SERIF }}
          >
            The MBA That{" "}
            <span className="relative inline-block">
              <span className="relative z-10 italic">Pays for Itself</span>
              <span
                aria-hidden
                className="absolute inset-x-0 bottom-1 -z-0 h-[0.45em]"
                style={{ background: "#F4C641", opacity: 0.55 }}
              />
            </span>{" "}
            Before You Graduate.
          </h1>
          <p
            className="mt-10 max-w-[62ch] text-[clamp(1.05rem,1.4vw,1.25rem)] leading-[1.6]"
            style={{ color: MUTED }}
          >
            Masters&apos; Union PG students generate real revenue, manage a ₹5 Cr investment fund,
            build personal brands with 46M+ reach, and step into roles at Bain, Google, and Goldman
            — with a 3.03x salary jump.
          </p>

          {/* CTAs */}
          <div className="mt-10 flex flex-wrap items-center gap-3">
            <a
              href="#apply"
              className="rounded-full px-6 py-3 text-[12px] uppercase tracking-[0.22em] text-white"
              style={{ background: INK, fontFamily: MONO }}
            >
              Apply for PG Programs
            </a>
            <a
              href="#brochure"
              className="rounded-full border px-6 py-3 text-[12px] uppercase tracking-[0.22em]"
              style={{ borderColor: INK, color: INK, fontFamily: MONO }}
            >
              Download Brochure
            </a>
          </div>

          {/* Stat strip */}
          <div
            className="mt-14 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border md:grid-cols-5"
            style={{ borderColor: RULE, background: RULE }}
          >
            {[
              ["₹33.39L", "Avg CTC"],
              ["₹61.98L", "Highest CTC"],
              ["3.03x", "Salary Jump"],
              ["148", "Recruiters"],
              ["35+", "International Offers"],
            ].map(([v, l]) => (
              <div key={l} className="px-5 py-7" style={{ background: PAPER }}>
                <div
                  className="text-[clamp(1.4rem,2.4vw,2rem)] leading-none tracking-[-0.02em]"
                  style={{ fontFamily: SERIF }}
                >
                  {v}
                </div>
                <div
                  className="mt-2 text-[10px] uppercase tracking-[0.22em]"
                  style={{ color: MUTED, fontFamily: MONO }}
                >
                  {l}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 2 — PROGRAMS */}
      <section style={{ background: CREAM }} className="border-y" >
        <div className="mx-auto max-w-7xl px-5 py-20 md:px-10 md:py-28">
          <div className="flex flex-col items-start justify-between gap-8 md:flex-row md:items-end">
            <div>
              <div
                className="text-[11px] uppercase tracking-[0.32em] opacity-70"
                style={{ fontFamily: MONO }}
              >
                Seven Programs
              </div>
              <h2
                className="mt-5 max-w-[20ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
                style={{ fontFamily: SERIF }}
              >
                Seven tracks. One model. Pick the domain — the intensity is the same.
              </h2>
            </div>
            {/* Tabs */}
            <div
              className="flex flex-wrap gap-2 rounded-full border p-1"
              style={{ borderColor: RULE, background: PAPER }}
            >
              {FILTERS.map((f) => {
                const active = filter === f.id;
                return (
                  <button
                    key={f.id}
                    onClick={() => setFilter(f.id)}
                    className="rounded-full px-4 py-2 text-[11px] uppercase tracking-[0.22em] transition-colors"
                    style={{
                      background: active ? INK : "transparent",
                      color: active ? PAPER : INK,
                      fontFamily: MONO,
                    }}
                  >
                    {f.label}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Grid */}
          <div className="mt-14 grid grid-cols-1 gap-6 md:grid-cols-2">
            {visible.map((p) => (
              <ProgramCard key={p.id} p={p} />
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 3 — HOW IT WORKS */}
      <section className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
        <div
          className="text-[11px] uppercase tracking-[0.32em] opacity-70"
          style={{ fontFamily: MONO }}
        >
          The Model
        </div>
        <h2
          className="mt-5 max-w-[22ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
          style={{ fontFamily: SERIF }}
        >
          Three forces that make MU different.
        </h2>
        <div className="mt-14 grid grid-cols-1 gap-px md:grid-cols-3" style={{ background: RULE }}>
          {[
            {
              k: "InClass",
              h: "Faculty Who've Done It",
              b: "30% professors from Harvard, Stanford, Wharton, Kellogg. 50% CEOs and operators. 20% PhD faculty. Every session is a real decision, not a case study.",
            },
            {
              k: "OutClass",
              h: "Your Grade Is Your Revenue",
              b: "No exams. Grades based on real products, real revenue, real NPS. You run businesses. You manage a fund. You build brands. You pitch to VCs.",
            },
            {
              k: "Immersions",
              h: "India & The World",
              b: "Full-term Bharat Immersion: 7,000 km, 8 hubs, 20+ cities, 40+ CXO sessions. Global: 8 immersions across 7 countries — INSEAD, Boeing, BMW, London finance desks.",
            },
          ].map((c) => (
            <div key={c.k} className="p-8 md:p-10" style={{ background: PAPER }}>
              <div
                className="text-[11px] uppercase tracking-[0.3em]"
                style={{ fontFamily: MONO, color: MUTED }}
              >
                {c.k}
              </div>
              <h3
                className="mt-4 text-[clamp(1.4rem,2vw,1.8rem)] leading-tight"
                style={{ fontFamily: SERIF }}
              >
                {c.h}
              </h3>
              <p className="mt-5 text-[1rem] leading-[1.65]" style={{ color: MUTED }}>
                {c.b}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* SECTION 4 — OUTCLASS */}
      <section style={{ background: INK, color: PAPER }}>
        <div className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
          <div
            className="text-[11px] uppercase tracking-[0.32em] opacity-70"
            style={{ fontFamily: MONO }}
          >
            OutClass
          </div>
          <h2
            className="mt-5 max-w-[22ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
            style={{ fontFamily: SERIF }}
          >
            What your peers built last year.
          </h2>
          <div className="mt-14 grid grid-cols-1 gap-px md:grid-cols-2" style={{ background: "rgba(255,255,255,0.12)" }}>
            {[
              {
                t: "Dropshipping Fair",
                s: "Term 1",
                b: "50 teams. Real products. Real customers. Cohort '25: ₹3.38 Cr total revenue.",
              },
              {
                t: "Content Creator Challenge",
                s: "Term 2",
                b: "120+ creators. 46M+ reach. ₹10L+ prize pool. Partnered with Perfora, Anveshan, WanderOn. 80+ live brand assets in 24 hours.",
              },
              {
                t: "Student Investment Fund",
                s: "Year-long",
                b: "₹5 Cr real corpus. Beaten public markets by 20–25% consistently. 5+ startup co-investments alongside VCs.",
              },
              {
                t: "Venture Initiation Programme",
                s: "Capstone",
                b: "₹25.24 Cr raised. ₹593 Cr combined portfolio valuation. 6 Shark Tank India appearances. 100+ VCs at Demo Day.",
              },
            ].map((x) => (
              <div key={x.t} className="p-8 md:p-10" style={{ background: INK }}>
                <div className="flex items-center justify-between">
                  <h3
                    className="text-[clamp(1.3rem,2vw,1.7rem)]"
                    style={{ fontFamily: SERIF }}
                  >
                    {x.t}
                  </h3>
                  <span
                    className="text-[10px] uppercase tracking-[0.22em] opacity-70"
                    style={{ fontFamily: MONO }}
                  >
                    {x.s}
                  </span>
                </div>
                <p className="mt-5 text-[1rem] leading-[1.65] opacity-85">{x.b}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 5 — PLACEMENTS */}
      <section className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
        <div
          className="text-[11px] uppercase tracking-[0.32em] opacity-70"
          style={{ fontFamily: MONO }}
        >
          Placements
        </div>
        <h2
          className="mt-5 max-w-[28ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
          style={{ fontFamily: SERIF }}
        >
          The numbers other schools don&apos;t put on their homepage.
        </h2>

        <div
          className="mt-14 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border md:grid-cols-6"
          style={{ borderColor: RULE, background: RULE }}
        >
          {[
            ["₹33.39L", "Average CTC"],
            ["₹61.98L", "Highest CTC"],
            ["3.03x", "Salary Jump"],
            ["148", "Recruiters"],
            ["35+", "Intl. Offers"],
            ["10–20%", "Annual Growth"],
          ].map(([v, l]) => (
            <div key={l} className="px-5 py-8" style={{ background: PAPER }}>
              <div
                className="text-[clamp(1.3rem,2vw,1.8rem)] leading-none tracking-[-0.02em]"
                style={{ fontFamily: SERIF }}
              >
                {v}
              </div>
              <div
                className="mt-2 text-[10px] uppercase tracking-[0.22em]"
                style={{ color: MUTED, fontFamily: MONO }}
              >
                {l}
              </div>
            </div>
          ))}
        </div>

        <div className="mt-14 grid grid-cols-1 gap-10 md:grid-cols-4">
          {[
            {
              k: "Consulting",
              v: "Bain · BCG · McKinsey · Accenture Strategy · EY-Parthenon · Kearney · PwC",
            },
            {
              k: "Finance / VC",
              v: "Axis Capital · Kotak IB · InnoVen Capital · WaterBridge Ventures · Avaana Capital",
            },
            {
              k: "Tech",
              v: "Google · Microsoft · Razorpay · Zepto · Zomato · MakeMyTrip",
            },
            {
              k: "International",
              v: "Google Dublin · Careem Dubai · Talabat Dubai · Avirom Capital US",
            },
          ].map((c) => (
            <div key={c.k}>
              <div
                className="text-[11px] uppercase tracking-[0.28em]"
                style={{ fontFamily: MONO, color: MUTED }}
              >
                {c.k}
              </div>
              <p className="mt-3 text-[1rem] leading-[1.6]">{c.v}</p>
            </div>
          ))}
        </div>
      </section>

      {/* SECTION 6 — IMMERSIONS */}
      <section style={{ background: CREAM }} className="border-y">
        <div className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
          <div
            className="text-[11px] uppercase tracking-[0.32em] opacity-70"
            style={{ fontFamily: MONO }}
          >
            Immersions
          </div>
          <h2
            className="mt-5 max-w-[24ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
            style={{ fontFamily: SERIF }}
          >
            Learn in boardrooms, on factory floors, and across continents.
          </h2>

          <div className="mt-14 grid grid-cols-1 gap-6 md:grid-cols-2">
            <div className="rounded-2xl border p-8 md:p-10" style={{ borderColor: RULE, background: PAPER }}>
              <h3 className="text-[clamp(1.4rem,2vw,1.8rem)]" style={{ fontFamily: SERIF }}>
                Bharat Immersion — 7,000 km across India
              </h3>
              <p className="mt-4 text-[1rem] leading-[1.65]" style={{ color: MUTED }}>
                A full academic term on the road. Route: Chandni Chowk → Dalal Street → Mundra&apos;s
                Adani ports → Darjeeling tea estates.
              </p>
              <div className="mt-6 flex flex-wrap gap-2">
                {["8 Hubs", "20+ Cities", "40+ CXO Sessions", "50+ One-Day Immersions", "Academic Credits"].map(
                  (c) => (
                    <span
                      key={c}
                      className="rounded-full border px-3 py-1.5 text-[11px]"
                      style={{ borderColor: RULE, fontFamily: MONO }}
                    >
                      {c}
                    </span>
                  ),
                )}
              </div>
            </div>
            <div className="rounded-2xl border p-8 md:p-10" style={{ borderColor: RULE, background: PAPER }}>
              <h3 className="text-[clamp(1.4rem,2vw,1.8rem)]" style={{ fontFamily: SERIF }}>
                Global Immersion — 8 immersions across 7 countries
              </h3>
              <p className="mt-4 text-[1rem] leading-[1.65]" style={{ color: MUTED }}>
                INSEAD Paris. London and New York finance desks. Boeing. BMW. SDA Bocconi.
              </p>
              <div className="mt-6 flex flex-wrap gap-2">
                {["Paris", "Singapore", "Boston", "Milan", "Berlin", "London", "Canada", "Academic Credits"].map(
                  (c) => (
                    <span
                      key={c}
                      className="rounded-full border px-3 py-1.5 text-[11px]"
                      style={{ borderColor: RULE, fontFamily: MONO }}
                    >
                      {c}
                    </span>
                  ),
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 7 — FACULTY */}
      <section className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
        <div
          className="text-[11px] uppercase tracking-[0.32em] opacity-70"
          style={{ fontFamily: MONO }}
        >
          Faculty
        </div>
        <h2
          className="mt-5 max-w-[22ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
          style={{ fontFamily: SERIF }}
        >
          Taught by the people running the industry.
        </h2>

        <div className="mt-14 grid grid-cols-1 gap-6 md:grid-cols-3">
          {[
            { p: "50%", h: "Industry Practitioners", b: "CEOs, founders, operators." },
            {
              p: "30%",
              h: "Full-Time Faculty",
              b: "PhD educators from IIM Calcutta, Bangalore, Ahmedabad.",
            },
            {
              p: "20%",
              h: "Visiting Faculty",
              b: "Harvard, Stanford, Wharton, Kellogg, Cornell, MIT Sloan, Imperial, Cambridge.",
            },
          ].map((x) => (
            <div
              key={x.h}
              className="rounded-2xl p-8"
              style={{ background: CREAM }}
            >
              <div
                className="text-[clamp(2.4rem,4vw,3.4rem)] leading-none tracking-[-0.02em]"
                style={{ fontFamily: SERIF }}
              >
                {x.p}
              </div>
              <div className="mt-4 text-[1.05rem]">{x.h}</div>
              <p className="mt-2 text-[0.95rem] leading-[1.6]" style={{ color: MUTED }}>
                {x.b}
              </p>
            </div>
          ))}
        </div>

        <blockquote
          className="mt-16 max-w-[60ch] text-balance text-[clamp(1.3rem,2.4vw,2rem)] italic leading-[1.3]"
          style={{ fontFamily: SERIF }}
        >
          &ldquo;Masters&apos; Union is doing something genuinely different. We&apos;ve brought
          Kellogg students here two years in a row.&rdquo;
          <footer
            className="mt-4 text-[11px] uppercase tracking-[0.22em] not-italic"
            style={{ fontFamily: MONO, color: MUTED }}
          >
            — Prof. Mohanbir Sawhney, Kellogg School of Management
          </footer>
        </blockquote>
      </section>

      {/* SECTION 8 — ALUMNI */}
      <section style={{ background: INK, color: PAPER }}>
        <div className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
          <div
            className="text-[11px] uppercase tracking-[0.32em] opacity-70"
            style={{ fontFamily: MONO }}
          >
            Alumni
          </div>
          <h2
            className="mt-5 max-w-[22ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
            style={{ fontFamily: SERIF }}
          >
            Not testimonials. Results.
          </h2>

          <div
            className="mt-14 grid grid-cols-1 gap-px md:grid-cols-3"
            style={{ background: "rgba(255,255,255,0.12)" }}
          >
            {[
              ["Jeneesha Singh", "Associate Consultant, Bain & Company", "Co'23"],
              ["Daniel Paul Nath", "Growth Strategist, Google Dublin", "Co'24"],
              ["Dharmil Bavishi", "Founder, Bullspree · Shark Tank S2", "Co'21"],
              ["Prashasti Singh", "Consultant, McKinsey", "Co'23"],
              ["Gautam Marwah", "Chief of Staff, Kae Capital", "Co'24"],
              ["Radika Agarwal", "Investment Analyst, Good Capital", "Co'24"],
            ].map(([n, r, c]) => (
              <div key={n} className="p-8" style={{ background: INK }}>
                <div className="text-[1.1rem]" style={{ fontFamily: SERIF }}>
                  {n}
                </div>
                <div className="mt-2 text-[0.95rem] opacity-85">{r}</div>
                <div
                  className="mt-3 text-[10px] uppercase tracking-[0.22em] opacity-70"
                  style={{ fontFamily: MONO }}
                >
                  {c}
                </div>
              </div>
            ))}
          </div>

          <p
            className="mt-12 text-[clamp(1.1rem,1.6vw,1.4rem)] italic opacity-90"
            style={{ fontFamily: SERIF }}
          >
            &ldquo;12% of every cohort goes directly into VC and investment roles.&rdquo;
          </p>
        </div>
      </section>

      {/* SECTION 9 — COHORT */}
      <section className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
        <div
          className="text-[11px] uppercase tracking-[0.32em] opacity-70"
          style={{ fontFamily: MONO }}
        >
          Cohort Profile
        </div>
        <h2
          className="mt-5 max-w-[22ch] text-balance text-[clamp(2rem,5vw,3.6rem)] leading-[1] tracking-[-0.02em]"
          style={{ fontFamily: SERIF }}
        >
          Who you&apos;ll learn with.
        </h2>

        <div
          className="mt-14 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border md:grid-cols-4"
          style={{ borderColor: RULE, background: RULE }}
        >
          {[
            ["24.5", "Avg Age (Years)"],
            ["3.7", "Avg Work Exp (Years)"],
            ["31%", "Female Representation"],
            ["5", "Backgrounds Represented"],
          ].map(([v, l]) => (
            <div key={l} className="px-5 py-8" style={{ background: PAPER }}>
              <div
                className="text-[clamp(1.6rem,2.4vw,2.2rem)] leading-none tracking-[-0.02em]"
                style={{ fontFamily: SERIF }}
              >
                {v}
              </div>
              <div
                className="mt-2 text-[10px] uppercase tracking-[0.22em]"
                style={{ color: MUTED, fontFamily: MONO }}
              >
                {l}
              </div>
            </div>
          ))}
        </div>

        <p className="mt-10 max-w-[60ch] text-[1.05rem]" style={{ color: MUTED }}>
          Backgrounds: Consulting · Finance · Tech · Startups · Family Business.
        </p>
        <p
          className="mt-6 text-[clamp(1.2rem,2vw,1.6rem)] italic"
          style={{ fontFamily: SERIF }}
        >
          Small cohort. High bar. Everyone here chose MU over conventional options.
        </p>
      </section>

      {/* SECTION 10 — ACCREDITATIONS */}
      <section style={{ background: CREAM }} className="border-y">
        <div className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32">
          <div
            className="text-[11px] uppercase tracking-[0.32em] opacity-70"
            style={{ fontFamily: MONO }}
          >
            Accreditations
          </div>
          <div className="mt-10 grid grid-cols-1 gap-10 md:grid-cols-2">
            <div className="rounded-2xl border p-8" style={{ borderColor: RULE, background: PAPER }}>
              <div className="text-[1.6rem]" style={{ fontFamily: SERIF }}>
                EFMD Accredited
              </div>
              <p className="mt-2 text-[0.95rem]" style={{ color: MUTED }}>
                Same body as INSEAD, LBS, HEC Paris.
              </p>
            </div>
            <div className="rounded-2xl border p-8" style={{ borderColor: RULE, background: PAPER }}>
              <div className="text-[1.6rem]" style={{ fontFamily: SERIF }}>
                AACSB Member
              </div>
              <p className="mt-2 text-[0.95rem]" style={{ color: MUTED }}>
                Same body as Harvard, Wharton, Stanford.
              </p>
            </div>
          </div>

          <div className="mt-12">
            <div
              className="text-[11px] uppercase tracking-[0.28em]"
              style={{ fontFamily: MONO, color: MUTED }}
            >
              Convocation Speakers
            </div>
            <p className="mt-4 text-[clamp(1.1rem,1.6vw,1.4rem)] leading-[1.5]" style={{ fontFamily: SERIF }}>
              Nithin Kamath (Zerodha) · Sanjeev Bikhchandani (Info Edge) · Peyush Bansal (Lenskart) ·
              Shri Jagdeep Dhankar (Vice President of India).
            </p>
          </div>
        </div>
      </section>

      {/* SECTION 11 — FINAL CTA */}
      <section id="apply" className="relative overflow-hidden" style={{ background: INK, color: PAPER }}>
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 opacity-30"
          style={{ background: GRADIENT, filter: "blur(120px)" }}
        />
        <div className="relative mx-auto max-w-5xl px-5 py-28 text-center md:px-10 md:py-36">
          <h2
            className="mx-auto max-w-[22ch] text-balance text-[clamp(2.2rem,5.4vw,4.4rem)] leading-[1] tracking-[-0.02em]"
            style={{ fontFamily: SERIF }}
          >
            The next cohort is forming. Your seat isn&apos;t reserved.
          </h2>
          <p className="mx-auto mt-6 max-w-[52ch] text-[1.05rem] opacity-85">
            Applications close when the cohort fills. Every batch has sold out.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-3">
            <a
              href="#"
              className="rounded-full px-7 py-3 text-[12px] uppercase tracking-[0.22em]"
              style={{ background: PAPER, color: INK, fontFamily: MONO }}
            >
              Apply Now
            </a>
            <a
              href="#"
              className="rounded-full border px-7 py-3 text-[12px] uppercase tracking-[0.22em]"
              style={{ borderColor: "rgba(255,255,255,0.4)", color: PAPER, fontFamily: MONO }}
            >
              Talk to Admissions
            </a>
          </div>
          <div
            className="mt-10 text-[11px] uppercase tracking-[0.24em] opacity-70"
            style={{ fontFamily: MONO }}
          >
            EFMD Accredited · AACSB Member · 148 Recruiters · ₹61.98L Highest CTC
          </div>
        </div>
      </section>
    </main>
  );
}

// ——————————————————————————————————————————————————————————
function ProgramCard({ p }: { p: Program }) {
  return (
    <article
      className="group relative flex flex-col overflow-hidden rounded-2xl border p-8 transition-colors md:p-10"
      style={{ borderColor: RULE, background: PAPER }}
    >
      <div
        aria-hidden
        className="absolute inset-x-0 top-0 h-[3px]"
        style={{ background: GRADIENT }}
      />
      <div className="flex items-center justify-between">
        <div
          className="text-[11px] uppercase tracking-[0.28em]"
          style={{ fontFamily: MONO, color: MUTED }}
        >
          No. {p.no}
        </div>
        <span
          className="rounded-full border px-3 py-1 text-[10px] uppercase tracking-[0.22em]"
          style={{ borderColor: RULE, fontFamily: MONO, color: MUTED }}
        >
          {p.tag}
        </span>
      </div>
      <h3
        className="mt-6 text-balance text-[clamp(1.4rem,2.2vw,1.9rem)] leading-[1.1] tracking-[-0.01em]"
        style={{ fontFamily: SERIF }}
      >
        {p.title}
      </h3>
      <p
        className="mt-3 text-[1rem] italic leading-[1.5]"
        style={{ color: MUTED, fontFamily: SERIF }}
      >
        {p.hook}
      </p>
      <ul className="mt-6 space-y-3">
        {p.bullets.map((b) => (
          <li key={b} className="flex items-start gap-3 text-[0.95rem] leading-[1.55]">
            <span
              aria-hidden
              className="mt-[0.55rem] inline-block h-[6px] w-[6px] flex-none rounded-full"
              style={{ background: INK }}
            />
            <span>{b}</span>
          </li>
        ))}
      </ul>
      <div className="mt-8">
        <a
          href="#"
          className="inline-flex items-center gap-2 text-[11px] uppercase tracking-[0.24em]"
          style={{ fontFamily: MONO }}
        >
          <span
            className="bg-clip-text text-transparent"
            style={{ backgroundImage: GRADIENT }}
          >
            {p.cta}
          </span>
          <span aria-hidden style={{ color: INK }}>→</span>
        </a>
      </div>
    </article>
  );
}
