/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as MuVenturesRouteImport } from './routes/mu-ventures'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LifeAtMuRouteImport } from './routes/life-at-mu'
import { Route as ImmersionsRouteImport } from './routes/immersions'
import { Route as HowWeTeachRouteImport } from './routes/how-we-teach'
import { Route as FoodLabRouteImport } from './routes/food-lab'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as D2cChallengeRouteImport } from './routes/d2c-challenge'
import { Route as CreatorChallengeRouteImport } from './routes/creator-challenge'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as Applications_centerRouteImport } from './routes/applications_center'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesUndergraduateTechnologyAndBusinessManagementRouteImport } from './routes/programmes.undergraduate.technology-and-business-management'
import { Route as ProgrammesUndergraduatePsychologyAndMarketingRouteImport } from './routes/programmes.undergraduate.psychology-and-marketing'
import { Route as ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRouteImport } from './routes/programmes.undergraduate.data-science-and-artificial-intelligence'
import { Route as ProgrammesPgUiUxAndAiProductDesignRouteImport } from './routes/programmes.pg.ui-ux-and-ai-product-design'
import { Route as ProgrammesPgSustainabilityAndBusinessManagementRouteImport } from './routes/programmes.pg.sustainability-and-business-management'
import { Route as ProgrammesPgSportsManagementAndGamingRouteImport } from './routes/programmes.pg.sports-management-and-gaming'
import { Route as ProgrammesPgPgpTbmRouteImport } from './routes/programmes.pg.pgp-tbm'
import { Route as ProgrammesPgHrAndOrganisationStrategyRouteImport } from './routes/programmes.pg.hr-and-organisation-strategy'
import { Route as ProgrammesPgAppliedAiAndAgenticSystemsRouteImport } from './routes/programmes.pg.applied-ai-and-agentic-systems'
import { Route as ProgrammesImmersionsPgpTbmSummerSchoolRouteImport } from './routes/programmes.immersions.pgp-tbm-summer-school'
import { Route as ProgrammesImmersionsPgpBharatRouteImport } from './routes/programmes.immersions.pgp-bharat'
import { Route as ProgrammesImmersionsBharatSummerFellowshipRouteImport } from './routes/programmes.immersions.bharat-summer-fellowship'
import { Route as ProgrammesExecutivePgpRiseGeneralManagementGlobalRouteImport } from './routes/programmes.executive.pgp-rise-general-management-global'
import { Route as ProgrammesExecutivePgpRiseGeneralManagementRouteImport } from './routes/programmes.executive.pgp-rise-general-management'
import { Route as ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRouteImport } from './routes/programmes.executive.entrepreneurship-and-business-acceleration'
import { Route as ProgrammesExecutiveCapitalMarketsAndTradingRouteImport } from './routes/programmes.executive.capital-markets-and-trading'
import { Route as ProgrammesExecutiveBloombergEquityResearchRouteImport } from './routes/programmes.executive.bloomberg-equity-research'
import { Route as ProgrammesExecutiveAiAndGccTransformationRouteImport } from './routes/programmes.executive.ai-and-gcc-transformation'

const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const MuVenturesRoute = MuVenturesRouteImport.update({
  id: '/mu-ventures',
  path: '/mu-ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeAtMuRoute = LifeAtMuRouteImport.update({
  id: '/life-at-mu',
  path: '/life-at-mu',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmersionsRoute = ImmersionsRouteImport.update({
  id: '/immersions',
  path: '/immersions',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeTeachRoute = HowWeTeachRouteImport.update({
  id: '/how-we-teach',
  path: '/how-we-teach',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodLabRoute = FoodLabRouteImport.update({
  id: '/food-lab',
  path: '/food-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const D2cChallengeRoute = D2cChallengeRouteImport.update({
  id: '/d2c-challenge',
  path: '/d2c-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorChallengeRoute = CreatorChallengeRouteImport.update({
  id: '/creator-challenge',
  path: '/creator-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const Applications_centerRoute = Applications_centerRouteImport.update({
  id: '/applications_center',
  path: '/applications_center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesUndergraduateTechnologyAndBusinessManagementRoute =
  ProgrammesUndergraduateTechnologyAndBusinessManagementRouteImport.update({
    id: '/programmes/undergraduate/technology-and-business-management',
    path: '/programmes/undergraduate/technology-and-business-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesUndergraduatePsychologyAndMarketingRoute =
  ProgrammesUndergraduatePsychologyAndMarketingRouteImport.update({
    id: '/programmes/undergraduate/psychology-and-marketing',
    path: '/programmes/undergraduate/psychology-and-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute =
  ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRouteImport.update(
    {
      id: '/programmes/undergraduate/data-science-and-artificial-intelligence',
      path: '/programmes/undergraduate/data-science-and-artificial-intelligence',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ProgrammesPgUiUxAndAiProductDesignRoute =
  ProgrammesPgUiUxAndAiProductDesignRouteImport.update({
    id: '/programmes/pg/ui-ux-and-ai-product-design',
    path: '/programmes/pg/ui-ux-and-ai-product-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesPgSustainabilityAndBusinessManagementRoute =
  ProgrammesPgSustainabilityAndBusinessManagementRouteImport.update({
    id: '/programmes/pg/sustainability-and-business-management',
    path: '/programmes/pg/sustainability-and-business-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesPgSportsManagementAndGamingRoute =
  ProgrammesPgSportsManagementAndGamingRouteImport.update({
    id: '/programmes/pg/sports-management-and-gaming',
    path: '/programmes/pg/sports-management-and-gaming',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesPgPgpTbmRoute = ProgrammesPgPgpTbmRouteImport.update({
  id: '/programmes/pg/pgp-tbm',
  path: '/programmes/pg/pgp-tbm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesPgHrAndOrganisationStrategyRoute =
  ProgrammesPgHrAndOrganisationStrategyRouteImport.update({
    id: '/programmes/pg/hr-and-organisation-strategy',
    path: '/programmes/pg/hr-and-organisation-strategy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesPgAppliedAiAndAgenticSystemsRoute =
  ProgrammesPgAppliedAiAndAgenticSystemsRouteImport.update({
    id: '/programmes/pg/applied-ai-and-agentic-systems',
    path: '/programmes/pg/applied-ai-and-agentic-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesImmersionsPgpTbmSummerSchoolRoute =
  ProgrammesImmersionsPgpTbmSummerSchoolRouteImport.update({
    id: '/programmes/immersions/pgp-tbm-summer-school',
    path: '/programmes/immersions/pgp-tbm-summer-school',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesImmersionsPgpBharatRoute =
  ProgrammesImmersionsPgpBharatRouteImport.update({
    id: '/programmes/immersions/pgp-bharat',
    path: '/programmes/immersions/pgp-bharat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesImmersionsBharatSummerFellowshipRoute =
  ProgrammesImmersionsBharatSummerFellowshipRouteImport.update({
    id: '/programmes/immersions/bharat-summer-fellowship',
    path: '/programmes/immersions/bharat-summer-fellowship',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute =
  ProgrammesExecutivePgpRiseGeneralManagementGlobalRouteImport.update({
    id: '/programmes/executive/pgp-rise-general-management-global',
    path: '/programmes/executive/pgp-rise-general-management-global',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesExecutivePgpRiseGeneralManagementRoute =
  ProgrammesExecutivePgpRiseGeneralManagementRouteImport.update({
    id: '/programmes/executive/pgp-rise-general-management',
    path: '/programmes/executive/pgp-rise-general-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute =
  ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRouteImport.update({
    id: '/programmes/executive/entrepreneurship-and-business-acceleration',
    path: '/programmes/executive/entrepreneurship-and-business-acceleration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesExecutiveCapitalMarketsAndTradingRoute =
  ProgrammesExecutiveCapitalMarketsAndTradingRouteImport.update({
    id: '/programmes/executive/capital-markets-and-trading',
    path: '/programmes/executive/capital-markets-and-trading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesExecutiveBloombergEquityResearchRoute =
  ProgrammesExecutiveBloombergEquityResearchRouteImport.update({
    id: '/programmes/executive/bloomberg-equity-research',
    path: '/programmes/executive/bloomberg-equity-research',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesExecutiveAiAndGccTransformationRoute =
  ProgrammesExecutiveAiAndGccTransformationRouteImport.update({
    id: '/programmes/executive/ai-and-gcc-transformation',
    path: '/programmes/executive/ai-and-gcc-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications_center': typeof Applications_centerRoute
  '/campus': typeof CampusRoute
  '/creator-challenge': typeof CreatorChallengeRoute
  '/d2c-challenge': typeof D2cChallengeRoute
  '/faculty': typeof FacultyRoute
  '/food-lab': typeof FoodLabRoute
  '/how-we-teach': typeof HowWeTeachRoute
  '/immersions': typeof ImmersionsRoute
  '/life-at-mu': typeof LifeAtMuRoute
  '/mentors': typeof MentorsRoute
  '/mu-ventures': typeof MuVenturesRoute
  '/placements': typeof PlacementsRoute
  '/startups': typeof StartupsRoute
  '/programmes/executive/ai-and-gcc-transformation': typeof ProgrammesExecutiveAiAndGccTransformationRoute
  '/programmes/executive/bloomberg-equity-research': typeof ProgrammesExecutiveBloombergEquityResearchRoute
  '/programmes/executive/capital-markets-and-trading': typeof ProgrammesExecutiveCapitalMarketsAndTradingRoute
  '/programmes/executive/entrepreneurship-and-business-acceleration': typeof ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute
  '/programmes/executive/pgp-rise-general-management': typeof ProgrammesExecutivePgpRiseGeneralManagementRoute
  '/programmes/executive/pgp-rise-general-management-global': typeof ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute
  '/programmes/immersions/bharat-summer-fellowship': typeof ProgrammesImmersionsBharatSummerFellowshipRoute
  '/programmes/immersions/pgp-bharat': typeof ProgrammesImmersionsPgpBharatRoute
  '/programmes/immersions/pgp-tbm-summer-school': typeof ProgrammesImmersionsPgpTbmSummerSchoolRoute
  '/programmes/pg/applied-ai-and-agentic-systems': typeof ProgrammesPgAppliedAiAndAgenticSystemsRoute
  '/programmes/pg/hr-and-organisation-strategy': typeof ProgrammesPgHrAndOrganisationStrategyRoute
  '/programmes/pg/pgp-tbm': typeof ProgrammesPgPgpTbmRoute
  '/programmes/pg/sports-management-and-gaming': typeof ProgrammesPgSportsManagementAndGamingRoute
  '/programmes/pg/sustainability-and-business-management': typeof ProgrammesPgSustainabilityAndBusinessManagementRoute
  '/programmes/pg/ui-ux-and-ai-product-design': typeof ProgrammesPgUiUxAndAiProductDesignRoute
  '/programmes/undergraduate/data-science-and-artificial-intelligence': typeof ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute
  '/programmes/undergraduate/psychology-and-marketing': typeof ProgrammesUndergraduatePsychologyAndMarketingRoute
  '/programmes/undergraduate/technology-and-business-management': typeof ProgrammesUndergraduateTechnologyAndBusinessManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications_center': typeof Applications_centerRoute
  '/campus': typeof CampusRoute
  '/creator-challenge': typeof CreatorChallengeRoute
  '/d2c-challenge': typeof D2cChallengeRoute
  '/faculty': typeof FacultyRoute
  '/food-lab': typeof FoodLabRoute
  '/how-we-teach': typeof HowWeTeachRoute
  '/immersions': typeof ImmersionsRoute
  '/life-at-mu': typeof LifeAtMuRoute
  '/mentors': typeof MentorsRoute
  '/mu-ventures': typeof MuVenturesRoute
  '/placements': typeof PlacementsRoute
  '/startups': typeof StartupsRoute
  '/programmes/executive/ai-and-gcc-transformation': typeof ProgrammesExecutiveAiAndGccTransformationRoute
  '/programmes/executive/bloomberg-equity-research': typeof ProgrammesExecutiveBloombergEquityResearchRoute
  '/programmes/executive/capital-markets-and-trading': typeof ProgrammesExecutiveCapitalMarketsAndTradingRoute
  '/programmes/executive/entrepreneurship-and-business-acceleration': typeof ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute
  '/programmes/executive/pgp-rise-general-management': typeof ProgrammesExecutivePgpRiseGeneralManagementRoute
  '/programmes/executive/pgp-rise-general-management-global': typeof ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute
  '/programmes/immersions/bharat-summer-fellowship': typeof ProgrammesImmersionsBharatSummerFellowshipRoute
  '/programmes/immersions/pgp-bharat': typeof ProgrammesImmersionsPgpBharatRoute
  '/programmes/immersions/pgp-tbm-summer-school': typeof ProgrammesImmersionsPgpTbmSummerSchoolRoute
  '/programmes/pg/applied-ai-and-agentic-systems': typeof ProgrammesPgAppliedAiAndAgenticSystemsRoute
  '/programmes/pg/hr-and-organisation-strategy': typeof ProgrammesPgHrAndOrganisationStrategyRoute
  '/programmes/pg/pgp-tbm': typeof ProgrammesPgPgpTbmRoute
  '/programmes/pg/sports-management-and-gaming': typeof ProgrammesPgSportsManagementAndGamingRoute
  '/programmes/pg/sustainability-and-business-management': typeof ProgrammesPgSustainabilityAndBusinessManagementRoute
  '/programmes/pg/ui-ux-and-ai-product-design': typeof ProgrammesPgUiUxAndAiProductDesignRoute
  '/programmes/undergraduate/data-science-and-artificial-intelligence': typeof ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute
  '/programmes/undergraduate/psychology-and-marketing': typeof ProgrammesUndergraduatePsychologyAndMarketingRoute
  '/programmes/undergraduate/technology-and-business-management': typeof ProgrammesUndergraduateTechnologyAndBusinessManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications_center': typeof Applications_centerRoute
  '/campus': typeof CampusRoute
  '/creator-challenge': typeof CreatorChallengeRoute
  '/d2c-challenge': typeof D2cChallengeRoute
  '/faculty': typeof FacultyRoute
  '/food-lab': typeof FoodLabRoute
  '/how-we-teach': typeof HowWeTeachRoute
  '/immersions': typeof ImmersionsRoute
  '/life-at-mu': typeof LifeAtMuRoute
  '/mentors': typeof MentorsRoute
  '/mu-ventures': typeof MuVenturesRoute
  '/placements': typeof PlacementsRoute
  '/startups': typeof StartupsRoute
  '/programmes/executive/ai-and-gcc-transformation': typeof ProgrammesExecutiveAiAndGccTransformationRoute
  '/programmes/executive/bloomberg-equity-research': typeof ProgrammesExecutiveBloombergEquityResearchRoute
  '/programmes/executive/capital-markets-and-trading': typeof ProgrammesExecutiveCapitalMarketsAndTradingRoute
  '/programmes/executive/entrepreneurship-and-business-acceleration': typeof ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute
  '/programmes/executive/pgp-rise-general-management': typeof ProgrammesExecutivePgpRiseGeneralManagementRoute
  '/programmes/executive/pgp-rise-general-management-global': typeof ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute
  '/programmes/immersions/bharat-summer-fellowship': typeof ProgrammesImmersionsBharatSummerFellowshipRoute
  '/programmes/immersions/pgp-bharat': typeof ProgrammesImmersionsPgpBharatRoute
  '/programmes/immersions/pgp-tbm-summer-school': typeof ProgrammesImmersionsPgpTbmSummerSchoolRoute
  '/programmes/pg/applied-ai-and-agentic-systems': typeof ProgrammesPgAppliedAiAndAgenticSystemsRoute
  '/programmes/pg/hr-and-organisation-strategy': typeof ProgrammesPgHrAndOrganisationStrategyRoute
  '/programmes/pg/pgp-tbm': typeof ProgrammesPgPgpTbmRoute
  '/programmes/pg/sports-management-and-gaming': typeof ProgrammesPgSportsManagementAndGamingRoute
  '/programmes/pg/sustainability-and-business-management': typeof ProgrammesPgSustainabilityAndBusinessManagementRoute
  '/programmes/pg/ui-ux-and-ai-product-design': typeof ProgrammesPgUiUxAndAiProductDesignRoute
  '/programmes/undergraduate/data-science-and-artificial-intelligence': typeof ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute
  '/programmes/undergraduate/psychology-and-marketing': typeof ProgrammesUndergraduatePsychologyAndMarketingRoute
  '/programmes/undergraduate/technology-and-business-management': typeof ProgrammesUndergraduateTechnologyAndBusinessManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications_center'
    | '/campus'
    | '/creator-challenge'
    | '/d2c-challenge'
    | '/faculty'
    | '/food-lab'
    | '/how-we-teach'
    | '/immersions'
    | '/life-at-mu'
    | '/mentors'
    | '/mu-ventures'
    | '/placements'
    | '/startups'
    | '/programmes/executive/ai-and-gcc-transformation'
    | '/programmes/executive/bloomberg-equity-research'
    | '/programmes/executive/capital-markets-and-trading'
    | '/programmes/executive/entrepreneurship-and-business-acceleration'
    | '/programmes/executive/pgp-rise-general-management'
    | '/programmes/executive/pgp-rise-general-management-global'
    | '/programmes/immersions/bharat-summer-fellowship'
    | '/programmes/immersions/pgp-bharat'
    | '/programmes/immersions/pgp-tbm-summer-school'
    | '/programmes/pg/applied-ai-and-agentic-systems'
    | '/programmes/pg/hr-and-organisation-strategy'
    | '/programmes/pg/pgp-tbm'
    | '/programmes/pg/sports-management-and-gaming'
    | '/programmes/pg/sustainability-and-business-management'
    | '/programmes/pg/ui-ux-and-ai-product-design'
    | '/programmes/undergraduate/data-science-and-artificial-intelligence'
    | '/programmes/undergraduate/psychology-and-marketing'
    | '/programmes/undergraduate/technology-and-business-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications_center'
    | '/campus'
    | '/creator-challenge'
    | '/d2c-challenge'
    | '/faculty'
    | '/food-lab'
    | '/how-we-teach'
    | '/immersions'
    | '/life-at-mu'
    | '/mentors'
    | '/mu-ventures'
    | '/placements'
    | '/startups'
    | '/programmes/executive/ai-and-gcc-transformation'
    | '/programmes/executive/bloomberg-equity-research'
    | '/programmes/executive/capital-markets-and-trading'
    | '/programmes/executive/entrepreneurship-and-business-acceleration'
    | '/programmes/executive/pgp-rise-general-management'
    | '/programmes/executive/pgp-rise-general-management-global'
    | '/programmes/immersions/bharat-summer-fellowship'
    | '/programmes/immersions/pgp-bharat'
    | '/programmes/immersions/pgp-tbm-summer-school'
    | '/programmes/pg/applied-ai-and-agentic-systems'
    | '/programmes/pg/hr-and-organisation-strategy'
    | '/programmes/pg/pgp-tbm'
    | '/programmes/pg/sports-management-and-gaming'
    | '/programmes/pg/sustainability-and-business-management'
    | '/programmes/pg/ui-ux-and-ai-product-design'
    | '/programmes/undergraduate/data-science-and-artificial-intelligence'
    | '/programmes/undergraduate/psychology-and-marketing'
    | '/programmes/undergraduate/technology-and-business-management'
  id:
    | '__root__'
    | '/'
    | '/applications_center'
    | '/campus'
    | '/creator-challenge'
    | '/d2c-challenge'
    | '/faculty'
    | '/food-lab'
    | '/how-we-teach'
    | '/immersions'
    | '/life-at-mu'
    | '/mentors'
    | '/mu-ventures'
    | '/placements'
    | '/startups'
    | '/programmes/executive/ai-and-gcc-transformation'
    | '/programmes/executive/bloomberg-equity-research'
    | '/programmes/executive/capital-markets-and-trading'
    | '/programmes/executive/entrepreneurship-and-business-acceleration'
    | '/programmes/executive/pgp-rise-general-management'
    | '/programmes/executive/pgp-rise-general-management-global'
    | '/programmes/immersions/bharat-summer-fellowship'
    | '/programmes/immersions/pgp-bharat'
    | '/programmes/immersions/pgp-tbm-summer-school'
    | '/programmes/pg/applied-ai-and-agentic-systems'
    | '/programmes/pg/hr-and-organisation-strategy'
    | '/programmes/pg/pgp-tbm'
    | '/programmes/pg/sports-management-and-gaming'
    | '/programmes/pg/sustainability-and-business-management'
    | '/programmes/pg/ui-ux-and-ai-product-design'
    | '/programmes/undergraduate/data-science-and-artificial-intelligence'
    | '/programmes/undergraduate/psychology-and-marketing'
    | '/programmes/undergraduate/technology-and-business-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Applications_centerRoute: typeof Applications_centerRoute
  CampusRoute: typeof CampusRoute
  CreatorChallengeRoute: typeof CreatorChallengeRoute
  D2cChallengeRoute: typeof D2cChallengeRoute
  FacultyRoute: typeof FacultyRoute
  FoodLabRoute: typeof FoodLabRoute
  HowWeTeachRoute: typeof HowWeTeachRoute
  ImmersionsRoute: typeof ImmersionsRoute
  LifeAtMuRoute: typeof LifeAtMuRoute
  MentorsRoute: typeof MentorsRoute
  MuVenturesRoute: typeof MuVenturesRoute
  PlacementsRoute: typeof PlacementsRoute
  StartupsRoute: typeof StartupsRoute
  ProgrammesExecutiveAiAndGccTransformationRoute: typeof ProgrammesExecutiveAiAndGccTransformationRoute
  ProgrammesExecutiveBloombergEquityResearchRoute: typeof ProgrammesExecutiveBloombergEquityResearchRoute
  ProgrammesExecutiveCapitalMarketsAndTradingRoute: typeof ProgrammesExecutiveCapitalMarketsAndTradingRoute
  ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute: typeof ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute
  ProgrammesExecutivePgpRiseGeneralManagementRoute: typeof ProgrammesExecutivePgpRiseGeneralManagementRoute
  ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute: typeof ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute
  ProgrammesImmersionsBharatSummerFellowshipRoute: typeof ProgrammesImmersionsBharatSummerFellowshipRoute
  ProgrammesImmersionsPgpBharatRoute: typeof ProgrammesImmersionsPgpBharatRoute
  ProgrammesImmersionsPgpTbmSummerSchoolRoute: typeof ProgrammesImmersionsPgpTbmSummerSchoolRoute
  ProgrammesPgAppliedAiAndAgenticSystemsRoute: typeof ProgrammesPgAppliedAiAndAgenticSystemsRoute
  ProgrammesPgHrAndOrganisationStrategyRoute: typeof ProgrammesPgHrAndOrganisationStrategyRoute
  ProgrammesPgPgpTbmRoute: typeof ProgrammesPgPgpTbmRoute
  ProgrammesPgSportsManagementAndGamingRoute: typeof ProgrammesPgSportsManagementAndGamingRoute
  ProgrammesPgSustainabilityAndBusinessManagementRoute: typeof ProgrammesPgSustainabilityAndBusinessManagementRoute
  ProgrammesPgUiUxAndAiProductDesignRoute: typeof ProgrammesPgUiUxAndAiProductDesignRoute
  ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute: typeof ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute
  ProgrammesUndergraduatePsychologyAndMarketingRoute: typeof ProgrammesUndergraduatePsychologyAndMarketingRoute
  ProgrammesUndergraduateTechnologyAndBusinessManagementRoute: typeof ProgrammesUndergraduateTechnologyAndBusinessManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mu-ventures': {
      id: '/mu-ventures'
      path: '/mu-ventures'
      fullPath: '/mu-ventures'
      preLoaderRoute: typeof MuVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-at-mu': {
      id: '/life-at-mu'
      path: '/life-at-mu'
      fullPath: '/life-at-mu'
      preLoaderRoute: typeof LifeAtMuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immersions': {
      id: '/immersions'
      path: '/immersions'
      fullPath: '/immersions'
      preLoaderRoute: typeof ImmersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-teach': {
      id: '/how-we-teach'
      path: '/how-we-teach'
      fullPath: '/how-we-teach'
      preLoaderRoute: typeof HowWeTeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-lab': {
      id: '/food-lab'
      path: '/food-lab'
      fullPath: '/food-lab'
      preLoaderRoute: typeof FoodLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d2c-challenge': {
      id: '/d2c-challenge'
      path: '/d2c-challenge'
      fullPath: '/d2c-challenge'
      preLoaderRoute: typeof D2cChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-challenge': {
      id: '/creator-challenge'
      path: '/creator-challenge'
      fullPath: '/creator-challenge'
      preLoaderRoute: typeof CreatorChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications_center': {
      id: '/applications_center'
      path: '/applications_center'
      fullPath: '/applications_center'
      preLoaderRoute: typeof Applications_centerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/undergraduate/technology-and-business-management': {
      id: '/programmes/undergraduate/technology-and-business-management'
      path: '/programmes/undergraduate/technology-and-business-management'
      fullPath: '/programmes/undergraduate/technology-and-business-management'
      preLoaderRoute: typeof ProgrammesUndergraduateTechnologyAndBusinessManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/undergraduate/psychology-and-marketing': {
      id: '/programmes/undergraduate/psychology-and-marketing'
      path: '/programmes/undergraduate/psychology-and-marketing'
      fullPath: '/programmes/undergraduate/psychology-and-marketing'
      preLoaderRoute: typeof ProgrammesUndergraduatePsychologyAndMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/undergraduate/data-science-and-artificial-intelligence': {
      id: '/programmes/undergraduate/data-science-and-artificial-intelligence'
      path: '/programmes/undergraduate/data-science-and-artificial-intelligence'
      fullPath: '/programmes/undergraduate/data-science-and-artificial-intelligence'
      preLoaderRoute: typeof ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/pg/ui-ux-and-ai-product-design': {
      id: '/programmes/pg/ui-ux-and-ai-product-design'
      path: '/programmes/pg/ui-ux-and-ai-product-design'
      fullPath: '/programmes/pg/ui-ux-and-ai-product-design'
      preLoaderRoute: typeof ProgrammesPgUiUxAndAiProductDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/pg/sustainability-and-business-management': {
      id: '/programmes/pg/sustainability-and-business-management'
      path: '/programmes/pg/sustainability-and-business-management'
      fullPath: '/programmes/pg/sustainability-and-business-management'
      preLoaderRoute: typeof ProgrammesPgSustainabilityAndBusinessManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/pg/sports-management-and-gaming': {
      id: '/programmes/pg/sports-management-and-gaming'
      path: '/programmes/pg/sports-management-and-gaming'
      fullPath: '/programmes/pg/sports-management-and-gaming'
      preLoaderRoute: typeof ProgrammesPgSportsManagementAndGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/pg/pgp-tbm': {
      id: '/programmes/pg/pgp-tbm'
      path: '/programmes/pg/pgp-tbm'
      fullPath: '/programmes/pg/pgp-tbm'
      preLoaderRoute: typeof ProgrammesPgPgpTbmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/pg/hr-and-organisation-strategy': {
      id: '/programmes/pg/hr-and-organisation-strategy'
      path: '/programmes/pg/hr-and-organisation-strategy'
      fullPath: '/programmes/pg/hr-and-organisation-strategy'
      preLoaderRoute: typeof ProgrammesPgHrAndOrganisationStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/pg/applied-ai-and-agentic-systems': {
      id: '/programmes/pg/applied-ai-and-agentic-systems'
      path: '/programmes/pg/applied-ai-and-agentic-systems'
      fullPath: '/programmes/pg/applied-ai-and-agentic-systems'
      preLoaderRoute: typeof ProgrammesPgAppliedAiAndAgenticSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/immersions/pgp-tbm-summer-school': {
      id: '/programmes/immersions/pgp-tbm-summer-school'
      path: '/programmes/immersions/pgp-tbm-summer-school'
      fullPath: '/programmes/immersions/pgp-tbm-summer-school'
      preLoaderRoute: typeof ProgrammesImmersionsPgpTbmSummerSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/immersions/pgp-bharat': {
      id: '/programmes/immersions/pgp-bharat'
      path: '/programmes/immersions/pgp-bharat'
      fullPath: '/programmes/immersions/pgp-bharat'
      preLoaderRoute: typeof ProgrammesImmersionsPgpBharatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/immersions/bharat-summer-fellowship': {
      id: '/programmes/immersions/bharat-summer-fellowship'
      path: '/programmes/immersions/bharat-summer-fellowship'
      fullPath: '/programmes/immersions/bharat-summer-fellowship'
      preLoaderRoute: typeof ProgrammesImmersionsBharatSummerFellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/executive/pgp-rise-general-management-global': {
      id: '/programmes/executive/pgp-rise-general-management-global'
      path: '/programmes/executive/pgp-rise-general-management-global'
      fullPath: '/programmes/executive/pgp-rise-general-management-global'
      preLoaderRoute: typeof ProgrammesExecutivePgpRiseGeneralManagementGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/executive/pgp-rise-general-management': {
      id: '/programmes/executive/pgp-rise-general-management'
      path: '/programmes/executive/pgp-rise-general-management'
      fullPath: '/programmes/executive/pgp-rise-general-management'
      preLoaderRoute: typeof ProgrammesExecutivePgpRiseGeneralManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/executive/entrepreneurship-and-business-acceleration': {
      id: '/programmes/executive/entrepreneurship-and-business-acceleration'
      path: '/programmes/executive/entrepreneurship-and-business-acceleration'
      fullPath: '/programmes/executive/entrepreneurship-and-business-acceleration'
      preLoaderRoute: typeof ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/executive/capital-markets-and-trading': {
      id: '/programmes/executive/capital-markets-and-trading'
      path: '/programmes/executive/capital-markets-and-trading'
      fullPath: '/programmes/executive/capital-markets-and-trading'
      preLoaderRoute: typeof ProgrammesExecutiveCapitalMarketsAndTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/executive/bloomberg-equity-research': {
      id: '/programmes/executive/bloomberg-equity-research'
      path: '/programmes/executive/bloomberg-equity-research'
      fullPath: '/programmes/executive/bloomberg-equity-research'
      preLoaderRoute: typeof ProgrammesExecutiveBloombergEquityResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/executive/ai-and-gcc-transformation': {
      id: '/programmes/executive/ai-and-gcc-transformation'
      path: '/programmes/executive/ai-and-gcc-transformation'
      fullPath: '/programmes/executive/ai-and-gcc-transformation'
      preLoaderRoute: typeof ProgrammesExecutiveAiAndGccTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Applications_centerRoute: Applications_centerRoute,
  CampusRoute: CampusRoute,
  CreatorChallengeRoute: CreatorChallengeRoute,
  D2cChallengeRoute: D2cChallengeRoute,
  FacultyRoute: FacultyRoute,
  FoodLabRoute: FoodLabRoute,
  HowWeTeachRoute: HowWeTeachRoute,
  ImmersionsRoute: ImmersionsRoute,
  LifeAtMuRoute: LifeAtMuRoute,
  MentorsRoute: MentorsRoute,
  MuVenturesRoute: MuVenturesRoute,
  PlacementsRoute: PlacementsRoute,
  StartupsRoute: StartupsRoute,
  ProgrammesExecutiveAiAndGccTransformationRoute:
    ProgrammesExecutiveAiAndGccTransformationRoute,
  ProgrammesExecutiveBloombergEquityResearchRoute:
    ProgrammesExecutiveBloombergEquityResearchRoute,
  ProgrammesExecutiveCapitalMarketsAndTradingRoute:
    ProgrammesExecutiveCapitalMarketsAndTradingRoute,
  ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute:
    ProgrammesExecutiveEntrepreneurshipAndBusinessAccelerationRoute,
  ProgrammesExecutivePgpRiseGeneralManagementRoute:
    ProgrammesExecutivePgpRiseGeneralManagementRoute,
  ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute:
    ProgrammesExecutivePgpRiseGeneralManagementGlobalRoute,
  ProgrammesImmersionsBharatSummerFellowshipRoute:
    ProgrammesImmersionsBharatSummerFellowshipRoute,
  ProgrammesImmersionsPgpBharatRoute: ProgrammesImmersionsPgpBharatRoute,
  ProgrammesImmersionsPgpTbmSummerSchoolRoute:
    ProgrammesImmersionsPgpTbmSummerSchoolRoute,
  ProgrammesPgAppliedAiAndAgenticSystemsRoute:
    ProgrammesPgAppliedAiAndAgenticSystemsRoute,
  ProgrammesPgHrAndOrganisationStrategyRoute:
    ProgrammesPgHrAndOrganisationStrategyRoute,
  ProgrammesPgPgpTbmRoute: ProgrammesPgPgpTbmRoute,
  ProgrammesPgSportsManagementAndGamingRoute:
    ProgrammesPgSportsManagementAndGamingRoute,
  ProgrammesPgSustainabilityAndBusinessManagementRoute:
    ProgrammesPgSustainabilityAndBusinessManagementRoute,
  ProgrammesPgUiUxAndAiProductDesignRoute:
    ProgrammesPgUiUxAndAiProductDesignRoute,
  ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute:
    ProgrammesUndergraduateDataScienceAndArtificialIntelligenceRoute,
  ProgrammesUndergraduatePsychologyAndMarketingRoute:
    ProgrammesUndergraduatePsychologyAndMarketingRoute,
  ProgrammesUndergraduateTechnologyAndBusinessManagementRoute:
    ProgrammesUndergraduateTechnologyAndBusinessManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
